#include "../../include/overworld_wild_behavior_data.h"

#include "../../include/config.h"
#include "../../include/constants/file.h"
#include "../../include/constants/maps.h"
#include "../../include/constants/species.h"

#ifdef IMPLEMENT_OVERWORLD_WILD_SPAWNS

static const u16 sOverworldWildEncounterAreaMapIds[] = {
    MAP_T20, MAP_R29, MAP_T21, MAP_R30,
    MAP_R31, MAP_T22, MAP_D15R0102, MAP_D15R0103,
    MAP_R32, MAP_D24R0101, MAP_D24, MAP_D24R0201,
    MAP_D24R0202, MAP_D24R0203, MAP_D24R0204, MAP_D25R0101,
    MAP_D25R0102, MAP_D25R0103, MAP_R33, MAP_D26R0101,
    MAP_D26R0102, MAP_D26R0103, MAP_D36R0101, MAP_R34,
    MAP_R35, MAP_D22R0101, MAP_D22R0102, MAP_D22R0103,
    MAP_R36, MAP_R37, MAP_T27, MAP_D18R0101,
    MAP_D18R0102, MAP_D17R0102, MAP_D17R0103, MAP_D17R0104,
    MAP_D17R0105, MAP_D17R0106, MAP_D17R0107, MAP_D17R0108,
    MAP_D17R0109, MAP_R38, MAP_R39, MAP_T26,
    MAP_W40, MAP_W41, MAP_D40R0101, MAP_D40R0102,
    MAP_D40R0104, MAP_D40R0107, MAP_T24, MAP_R42,
    MAP_D38R0101, MAP_D38R0102, MAP_D38R0103, MAP_D38R0104,
    MAP_R43, MAP_T29, MAP_R44, MAP_D39R0101,
    MAP_D39R0102, MAP_D39R0103, MAP_D39R0104, MAP_T30,
    MAP_D44R0101, MAP_D44R0102, MAP_R45, MAP_R46,
    MAP_D42R0102, MAP_D42R0101, MAP_R47, MAP_D11R0101,
    MAP_D11R0102, MAP_D11R0103, MAP_D11R0104, MAP_D11R0105,
    MAP_D41R0105, MAP_D41R0107, MAP_D41R0108, MAP_D50R0101,
    MAP_D17R0112, MAP_T31, MAP_D41R0101, MAP_D41R0102,
    MAP_D41R0103, MAP_D41R0104, MAP_SAF01, MAP_SAF02,
    MAP_SAF03, MAP_SAF04, MAP_SAF05, MAP_SAF06,
    MAP_SAF07, MAP_SAF08, MAP_SAF09, MAP_SAF10,
    MAP_SAF11, MAP_SAF12, MAP_SAF13, MAP_SAF14,
    MAP_R12, MAP_W19, MAP_W20, MAP_T01,
    MAP_T02, MAP_T04, MAP_T06, MAP_T07,
    MAP_T08, MAP_T09, MAP_R48, MAP_R26,
    MAP_R27, MAP_R28, MAP_D02R0101, MAP_D02R0102,
    MAP_D05R0101, MAP_D05R0102, MAP_D43R0101, MAP_R01,
    MAP_R02, MAP_R03, MAP_R04, MAP_R05,
    MAP_R06, MAP_R07, MAP_R08, MAP_R09,
    MAP_R10, MAP_R11, MAP_R13, MAP_R14,
    MAP_R15, MAP_R16, MAP_R17, MAP_R18,
    MAP_W21, MAP_R22, MAP_R24, MAP_R25,
    MAP_D45R0101, MAP_D45R0102, MAP_D01R0101, MAP_D43R0102,
    MAP_D43R0103, MAP_R02R0101, MAP_D46R0101, MAP_D03R0101,
    MAP_D03R0102, MAP_D03R0103,
};

static const u8 sOverworldWildEncounterAreaDataIds[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 18, 19, 20, 21, 22, 23, 24, 24, 25, 26, 27, 28,
    29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
    46, 48, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65,
    66, 66, 67, 68, 69, 70, 71, 74, 75, 76, 77, 78, 79, 80, 81, 83,
    84, 85, 86, 87, 87, 88, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
    91, 91, 91, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
    118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
    132, 132, 133, 134, 135, 136, 137, 139, 140, 141,
};

#define OW_WILD_ENCOUNTER_AREA_COUNT \
    (sizeof(sOverworldWildEncounterAreaMapIds) / sizeof(sOverworldWildEncounterAreaMapIds[0]))
#define OW_WILD_ENCOUNTER_AREA_DATA_COUNT \
    (sizeof(sOverworldWildEncounterAreaDataIds) / sizeof(sOverworldWildEncounterAreaDataIds[0]))

typedef char OverworldWildEncounterAreaCountMismatch[
    OW_WILD_ENCOUNTER_AREA_COUNT == OW_WILD_ENCOUNTER_AREA_DATA_COUNT ? 1 : -1];

#define OW_WILD_SPAWNER_MOVEMENT_RANGE 32
#define OW_WILD_SPAWNER_MOVEMENT_BURST_UPDATE_STEPS 32
#define OW_WILD_SPAWNER_MOVEMENT_FRAME_TASK_PRIORITY 1300
#define OW_WILD_SPAWNER_MOVEMENT_FRAME_DECISION_INTERVAL 1
#define OW_WILD_SPAWNER_MOVEMENT_MAX_DIRECTIONS 4
#define OW_WILD_SPAWNER_UNTANGLE_MAX_DIRECTIONS 4
#define OW_WILD_SPAWNER_BATTLE_SETTLE_FRAMES 0
#define OW_WILD_PLAYER_RELATIVE_SPAWN_MIN_DISTANCE 1
#define OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE 8
#define OW_WILD_SPAWNER_MOVEMENT_SLOT_MASK(slot) (1u << (slot))
#define OW_WILD_SPAWNER_MOVEMENT_LOOK_UP_COMMAND 0x00
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_1 1
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_2 2
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_3 3
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_4 4
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_DEFAULT 1
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_1_COMMAND 0x08
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_2_COMMAND 0x0C
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_3_COMMAND 0x10
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_4_COMMAND 0x14
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_1_STEP_FRAMES 16
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_2_STEP_FRAMES 8
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_3_STEP_FRAMES 4
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_4_STEP_FRAMES OW_WILD_SPAWNER_MOVEMENT_SPEED_3_STEP_FRAMES
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_3_DECISION_INTERVAL 2
#define OW_WILD_SPAWNER_MOVEMENT_SPEED_4_DECISION_INTERVAL 1
#define OW_WILD_SPAWNER_MOVEMENT_LEDGE_JUMP_COMMAND 0x38
#define OW_WILD_SPAWNER_CANOPY_HOPPER_JUMP_1_COMMAND 0x34
#define OW_WILD_SPAWNER_CANOPY_HOPPER_JUMP_2_COMMAND 0x38
#define OW_WILD_SPAWNER_CANOPY_HOPPER_TRAVEL_COMMAND OW_WILD_SPAWNER_CANOPY_HOPPER_JUMP_1_COMMAND
#define OW_WILD_SPAWNER_CANOPY_HOPPER_WAIT_JUMP_LEFT_2_COMMAND 0x5E
#define OW_WILD_SPAWNER_CANOPY_HOPPER_WAIT_JUMP_RIGHT_2_COMMAND 0x5F
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LOCK_DIR_COMMAND 0x47
#define OW_WILD_SPAWNER_CANOPY_HOPPER_RELEASE_DIR_COMMAND 0x48
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PARTNER_PREP_COMMAND 0x49
#define OW_WILD_SPAWNER_CANOPY_HOPPER_FREEZE_COMMAND 0x3E
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PARTNER_RESTORE_COMMAND 0x4A
#define OW_WILD_SPAWNER_CANOPY_HOPPER_MOVEMENT_END_COMMAND 0xFE
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_COMMAND OW_WILD_SPAWNER_CANOPY_HOPPER_JUMP_1_COMMAND
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_DELTA_FX32 0x2000
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_FRAMES_PER_TILE 8
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_TYPE 3
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_ARC_TABLE 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_ARC_FULL 0x1000
#define OW_WILD_SPAWNER_PIDGEY_MOVEMENT_SPEED 3
#define OW_WILD_SPAWNER_SPOT_RANGE 3
#define OW_WILD_SPAWNER_SWARM_SEEK_RADIUS 7
#define OW_WILD_SPAWNER_SWARM_GROUP_RADIUS 3
#define OW_WILD_SPAWNER_SWARM_INITIAL_SPAWN_COOLDOWN_FRAMES 0
#define OW_WILD_SPAWNER_SWARM_SPAWN_COOLDOWN_FRAMES 90
#define OW_WILD_SPAWNER_SWARM_MAX_EXTRA_SPAWNS 3
#define OW_WILD_SPAWNER_CLOSE_ALERT_RADIUS 1
#define OW_WILD_SPAWNER_SPOT_EMOTE_PARTNER_PREP_COMMAND 0x49
#define OW_WILD_SPAWNER_SPOT_EMOTE_JUMP_SITE_COMMAND 0x30
#define OW_WILD_SPAWNER_SPOT_EMOTE_FREEZE_COMMAND 0x3E
#define OW_WILD_SPAWNER_SPOT_EMOTE_PARTNER_RESTORE_COMMAND 0x4A
#define OW_WILD_SPAWNER_ALERT_TIME_AUTO 0
#define OW_WILD_SPAWNER_SPOT_EMOTE_FRAMES_PER_JUMP 64
#define OW_WILD_SPAWNER_SPOT_EMOTE_SPEECH_FRAMES 10
#define OW_WILD_SPAWNER_SPOT_EMOTE_JUMPS_DEFAULT 1
#define OW_WILD_SPAWNER_SPOT_EMOTE_JUMPS_SPEED_3 2
#define OW_WILD_SPAWNER_SPOT_EMOTE_SE SEQ_SE_GS_UFO_JUMP
#define OW_WILD_SPAWNER_HOP_START_SE SEQ_SE_DP_DANSA
#define OW_WILD_SPAWNER_CANOPY_HOP_RUSTLE_SE SEQ_SE_DP_FPASA2
#define OW_WILD_SPAWNER_CANOPY_HOP_BALLOON_SE SEQ_SE_PL_BALLOON03
#define OW_WILD_SPAWNER_CANOPY_HOP_SOUND_VARIANTS 2
#define OW_WILD_SPAWNER_HOP_START_SE_SUPPRESS_FRAMES 4
#define OW_WILD_SOUND_TESTER_TASK_PRIORITY 1299
#define OW_WILD_VISUAL_TESTER_ENABLED 0
#define OW_WILD_VISUAL_TESTER_VAR 0x8004
#define OW_WILD_VISUAL_TESTER_GENERIC_COUNT 4
#define OW_WILD_VISUAL_TESTER_MARK_FIRST 6
#define OW_WILD_VISUAL_TESTER_MARK_COUNT 4
#define OW_WILD_VISUAL_TESTER_FF070_FIRST 12
#define OW_WILD_VISUAL_TESTER_FF070_COUNT 4
#define OW_WILD_VISUAL_TESTER_FF8F0_FIRST 16
#define OW_WILD_VISUAL_TESTER_FF8F0_COUNT 4
#define OW_WILD_VISUAL_TESTER_FF0E4_FIRST 20
#define OW_WILD_VISUAL_TESTER_FF0E4_COUNT 2
#define OW_WILD_VISUAL_TESTER_220329C_FIRST 24
#define OW_WILD_VISUAL_TESTER_220329C_COUNT 4
#define OW_WILD_VISUAL_TESTER_BUBBLE_FIRST 28
#define OW_WILD_VISUAL_TESTER_BUBBLE_COUNT 14
#define OW_WILD_VISUAL_TESTER_FD2EC_EFFECT (OW_WILD_VISUAL_TESTER_BUBBLE_FIRST + OW_WILD_VISUAL_TESTER_BUBBLE_COUNT)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_0 (OW_WILD_VISUAL_TESTER_FD2EC_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_1 (OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_0 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_ALIAS_0 (OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_1 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_ALIAS_1 (OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_ALIAS_0 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_AVATAR_EFFECT (OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_ALIAS_1 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_AVATAR_WRAPPER (OW_WILD_VISUAL_TESTER_HEADBUTT_AVATAR_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_MARK_EXTRA_FIRST (OW_WILD_VISUAL_TESTER_HEADBUTT_AVATAR_WRAPPER + 1)
#define OW_WILD_VISUAL_TESTER_MARK_EXTRA_COUNT 4
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_EXTRA_FIRST (OW_WILD_VISUAL_TESTER_MARK_EXTRA_FIRST + OW_WILD_VISUAL_TESTER_MARK_EXTRA_COUNT)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_EXTRA_COUNT 4
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_FF070 (OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_EXTRA_FIRST + OW_WILD_VISUAL_TESTER_HEADBUTT_TASK_EXTRA_COUNT)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_FF8F0 (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_FF070 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_GROUND (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_FF8F0 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_LEAF_RESTART (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_GROUND + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_LEAF_WRAPPER (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_LEAF_RESTART + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_TASK_0 (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_LEAF_WRAPPER + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_TASK_1 (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_TASK_0 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_AVATAR_WRAPPER (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_TASK_1 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_AVATAR_EFFECT (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_AVATAR_WRAPPER + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_MARK_0 (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_AVATAR_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_MARK_1 (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_MARK_0 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_WAIT_JUMP (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_MARK_1 + 1)
#define OW_WILD_VISUAL_TESTER_FD640_EFFECT (OW_WILD_VISUAL_TESTER_HEADBUTT_SAFE_WAIT_JUMP + 1)
#define OW_WILD_VISUAL_TESTER_FD8E8_FIRST (OW_WILD_VISUAL_TESTER_FD640_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_FD8E8_COUNT 4
#define OW_WILD_VISUAL_TESTER_FDA74_FIRST (OW_WILD_VISUAL_TESTER_FD8E8_FIRST + OW_WILD_VISUAL_TESTER_FD8E8_COUNT)
#define OW_WILD_VISUAL_TESTER_FDA74_COUNT 4
#define OW_WILD_VISUAL_TESTER_FE3F8_FIRST (OW_WILD_VISUAL_TESTER_FDA74_FIRST + OW_WILD_VISUAL_TESTER_FDA74_COUNT)
#define OW_WILD_VISUAL_TESTER_FE3F8_COUNT 6
#define OW_WILD_VISUAL_TESTER_FF964_FIRST (OW_WILD_VISUAL_TESTER_FE3F8_FIRST + OW_WILD_VISUAL_TESTER_FE3F8_COUNT)
#define OW_WILD_VISUAL_TESTER_FF964_COUNT 4
#define OW_WILD_VISUAL_TESTER_FF4FC_EFFECT (OW_WILD_VISUAL_TESTER_FF964_FIRST + OW_WILD_VISUAL_TESTER_FF964_COUNT)
#define OW_WILD_VISUAL_TESTER_FECA0_EFFECT (OW_WILD_VISUAL_TESTER_FF4FC_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_FEE04_EFFECT (OW_WILD_VISUAL_TESTER_FECA0_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FDA14 (OW_WILD_VISUAL_TESTER_FEE04_EFFECT + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FE590 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FDA14 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_2203A18 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FE590 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_2203E40 (OW_WILD_VISUAL_TESTER_RAW_CTOR_2203A18 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FEA0C (OW_WILD_VISUAL_TESTER_RAW_CTOR_2203E40 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_22001E4 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FEA0C + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FEEEC (OW_WILD_VISUAL_TESTER_RAW_CTOR_22001E4 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FF464 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FEEEC + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FF6B0 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FF464 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FF854 (OW_WILD_VISUAL_TESTER_RAW_CTOR_FF6B0 + 1)
#define OW_WILD_VISUAL_TESTER_RAW_CTOR_FFC0C (OW_WILD_VISUAL_TESTER_RAW_CTOR_FF854 + 1)
#define OW_WILD_VISUAL_TESTER_HEADBUTT_LEAF_BURST (OW_WILD_VISUAL_TESTER_RAW_CTOR_FFC0C + 1)
#define OW_WILD_VISUAL_TESTER_COUNT (OW_WILD_VISUAL_TESTER_HEADBUTT_LEAF_BURST + 1)
#define OW_WILD_VISUAL_TESTER_TEMP_EFFECT_SLOTS 4
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_NONE 0
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_EFFECT 1
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FDA30 2
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FE5A4 3
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_2203A38 4
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_2203E64 5
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FEA20 6
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_22001F8 7
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FEF08 8
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FF480 9
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FF6CC 10
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FF870 11
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_FFC28 12
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_HEADBUTT_TASK 13
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_HEADBUTT_FIELD_TASK 14
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_HEADBUTT_LEAF_EFFECT 15
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_HEADBUTT_LEAF_DIRECTION 16
#define OW_WILD_VISUAL_TESTER_TEMP_CLEANUP_HEADBUTT_LEAF_WORK 17
#define OW_WILD_VISUAL_TESTER_HEADBUTT_MODE_NONE 0xFF
#define OW_WILD_VISUAL_TESTER_HEADBUTT_LEAF_DIRECTION_NONE 0xFFFF
#define OW_WILD_VISUAL_TESTER_CMD_BUFFER_NUMBERS 0
#define OW_WILD_VISUAL_TESTER_CMD_PLAY 1
#define OW_WILD_VISUAL_TESTER_CMD_NEXT_PLAY 2
#define OW_WILD_VISUAL_TESTER_CMD_PREVIOUS_PLAY 3
#define OW_WILD_VISUAL_TESTER_CMD_NEXT_16_PLAY 4
#define OW_WILD_VISUAL_TESTER_CMD_PREVIOUS_16_PLAY 5
#define OW_WILD_VISUAL_TESTER_CMD_NEXT_128_PLAY 6
#define OW_WILD_VISUAL_TESTER_CMD_PREVIOUS_128_PLAY 7
#define OW_WILD_VISUAL_TESTER_CMD_CLOSE 8
#define OW_WILD_VISUAL_TESTER_CMD_CLEAR_TEMPORARY_EFFECTS 9
#define OW_WILD_VISUAL_TESTER_CMD_TICK_TEMPORARY_EFFECTS 10
#define OW_WILD_HEADBUTT_LEAF_TASK_CREATE ((OverworldWildHeadbuttLeafTaskCreateFunc)0x02249459)
#define OW_WILD_HEADBUTT_LEAF_TASK_DONE ((OverworldWildHeadbuttLeafTaskDoneFunc)0x0224953D)
#define OW_WILD_HEADBUTT_LEAF_TASK_DESTROY ((OverworldWildHeadbuttLeafTaskDestroyFunc)0x02249549)
#define OW_WILD_HEADBUTT_LEAF_EFFECT_CREATE ((OverworldWildHeadbuttLeafEffectCreateFunc)0x022006A9)
#define OW_WILD_HEADBUTT_LEAF_EFFECT_DESTROY ((OverworldWildHeadbuttLeafEffectDestroyFunc)0x022006C5)
#define OW_WILD_EFFECT_CONTEXT_UPDATE ((OverworldWildEffectContextUpdateFunc)0x021F1611)
#define OW_WILD_PARTICLE_MANAGER_CREATE ((OverworldWildParticleManagerCreateFunc)0x020689C9)
#define OW_WILD_PARTICLE_MANAGER_DESTROY ((OverworldWildParticleManagerDestroyFunc)0x020689F9)
#define OW_WILD_PARTICLE_MANAGER_TICK ((OverworldWildParticleManagerTickFunc)0x02068BAD)
#define OW_WILD_HEADBUTT_LEAF_WORK_CREATE ((OverworldWildHeadbuttLeafWorkCreateFunc)0x0224955D)
#define OW_WILD_HEADBUTT_LEAF_TEMP_CREATE ((OverworldWildHeadbuttLeafTempCreateFunc)0x0224A075)
#define OW_WILD_HEADBUTT_LEAF_RESOURCE_SETUP ((OverworldWildHeadbuttLeafResourceSetupFunc)0x0224A081)
#define OW_WILD_HEADBUTT_LEAF_RESOURCE_DESTROY ((OverworldWildHeadbuttLeafResourceDestroyFunc)0x0224A289)
#define OW_WILD_HEADBUTT_LEAF_TEMP_DESTROY ((OverworldWildHeadbuttLeafTempDestroyFunc)0x0200770D)
#define OW_WILD_HEADBUTT_LEAF_BURST ((OverworldWildHeadbuttLeafBurstFunc)0x0224A9D9)
#define OW_WILD_HEADBUTT_PRESENTATION_TASK_CREATE ((OverworldWildHeadbuttPresentationTaskCreateFunc)0x021F2F71)
#define OW_WILD_HEADBUTT_PRESENTATION_TASK_DESTROY ((OverworldWildHeadbuttPresentationTaskDestroyFunc)0x021F2FF1)
#define OW_WILD_HEADBUTT_FIELD_TASK_DONE ((OverworldWildHeadbuttFieldTaskDoneFunc)0x021FC76D)
#define OW_WILD_HEADBUTT_FIELD_TASK_DESTROY ((OverworldWildHeadbuttFieldTaskDestroyFunc)0x021FC785)
#define OW_WILD_HEADBUTT_LEAF_BURST_FRAMES 96
#define OW_WILD_HEADBUTT_LEAF_WORK_TICK_ACTIVE_OFFSET 0x10
#define OW_WILD_HEADBUTT_LEAF_WORK_STATE_OFFSET 0x14
#define OW_WILD_HEADBUTT_LEAF_WORK_MODE_OFFSET 0x20
#define OW_WILD_HEADBUTT_LEAF_WORK_Y_MIN_OFFSET 0x4C
#define OW_WILD_HEADBUTT_LEAF_WORK_Y_MAX_OFFSET 0x50
#define OW_WILD_HEADBUTT_LEAF_WORK_OBJECT_OFFSET 0x5C
#define OW_WILD_HEADBUTT_LEAF_WORK_MANAGER_OFFSET 0x1E0
#define OW_WILD_HEADBUTT_LEAF_WORK_FACING_OFFSET 0x0C
#define OW_WILD_HEADBUTT_LEAF_WORK_FACING_BACKUP_OFFSET 0x0E
#define OW_WILD_HEADBUTT_LEAF_WORK_TICK_ACTIVE_STATE 1
#define OW_WILD_HEADBUTT_LEAF_WORK_ACTIVE_STATE 2
#define OW_WILD_HEADBUTT_LEAF_WORK_Y_MIN 0
#define OW_WILD_HEADBUTT_LEAF_WORK_Y_MAX (0x100 << 12)
#define OW_WILD_HEADBUTT_LEAF_PARTICLE_HEAP 4
#define OW_WILD_HEADBUTT_LEAF_PARTICLE_COUNT 32
#define OW_WILD_PLAYER_AVATAR_GET_STATE ((OverworldWildPlayerAvatarStateFunc)0x0205C701)
#define OW_WILD_PLAYER_AVATAR_GET_DISPLAY_STATE ((OverworldWildPlayerAvatarDisplayStateFunc)0x0205C99D)
#define OW_WILD_PLAYER_AVATAR_APPLY_DISPLAY_STATE ((OverworldWildPlayerAvatarApplyDisplayStateFunc)0x021F1AFD)
#define OW_WILD_PLAYER_AVATAR_REFRESH_DISPLAY ((OverworldWildPlayerAvatarRefreshFunc)0x021F1B05)
#define OW_WILD_PLAYER_AVATAR_RESTORE_MODE_0 ((OverworldWildPlayerAvatarRestoreFunc)0x021F1B39)
#define OW_WILD_PLAYER_AVATAR_RESTORE_MODE_3 ((OverworldWildPlayerAvatarRestoreFunc)0x021F1C31)
#define OW_WILD_MAP_OBJECT_UNPAUSE_MOVEMENT ((OverworldWildMapObjectMovementFunc)0x0205F709)
#define OW_WILD_SPAWNER_TIRED_AFTER_STEPS 5
#define OW_WILD_SPAWNER_TIRED_USE_FOLLOWER_BUBBLE 1
#define OW_WILD_SPAWNER_TIRED_USE_DIRECT_BUBBLE_CREATOR 1
#define OW_WILD_SPAWNER_TIRED_STOP_BUBBLE_SE 1
#define OW_WILD_SPAWNER_TIRED_PLAY_COOLDOWN_SE 0
#define OW_WILD_SPAWNER_BUBBLE_ID_HEART 0
#define OW_WILD_SPAWNER_BUBBLE_ID_SMILE 1
#define OW_WILD_SPAWNER_BUBBLE_ID_ANGRY 2
#define OW_WILD_SPAWNER_BUBBLE_ID_SAD 3
#define OW_WILD_SPAWNER_BUBBLE_ID_MILDLY_HAPPY 4
#define OW_WILD_SPAWNER_BUBBLE_ID_DISAPPROVAL 5
#define OW_WILD_SPAWNER_BUBBLE_ID_MUSIC_NOTE 6
#define OW_WILD_SPAWNER_BUBBLE_ID_QUESTION_MARK 7
#define OW_WILD_SPAWNER_BUBBLE_ID_EXCLAMATION_MARK 8
#define OW_WILD_SPAWNER_BUBBLE_ID_WATER_DROPLET 9
#define OW_WILD_SPAWNER_BUBBLE_ID_DESPAIR 10
#define OW_WILD_SPAWNER_BUBBLE_ID_POISON 11
#define OW_WILD_SPAWNER_BUBBLE_ID_ELLIPSIS 12
#define OW_WILD_SPAWNER_BUBBLE_ID_SLEEP 13
#define OW_WILD_SPAWNER_TIRED_BUBBLE_ID_PROBE 0
#define OW_WILD_SPAWNER_TIRED_BUBBLE_ID_PROBE_MIN OW_WILD_SPAWNER_BUBBLE_ID_HEART
#define OW_WILD_SPAWNER_TIRED_BUBBLE_ID_PROBE_MAX OW_WILD_SPAWNER_BUBBLE_ID_SLEEP
#define OW_WILD_SPAWNER_TIRED_BUBBLE_ID OW_WILD_SPAWNER_BUBBLE_ID_WATER_DROPLET
#define OW_WILD_SPAWNER_TIRED_EMOTE_COMMAND 0x65
#define OW_WILD_SPAWNER_TIRED_EMOTE_FRAMES 96
#define OW_WILD_SPAWNER_TIRED_SPOT_COOLDOWN_FRAMES 180
#define OW_WILD_SPAWNER_FLEE_TIRED_REST_TIME 4
#define OW_WILD_SPAWNER_ASLEEP_REST_TIMER 255
#define OW_WILD_SPAWNER_TIRED_WANDER_PAUSE_FRAMES 24
#define OW_WILD_SPAWNER_TIRED_EMOTE_SE SEQ_SE_PL_BALLOON05
#define OW_WILD_SPAWNER_CHILL_WANDER_COOLDOWN_FRAMES 32
#define OW_WILD_SPAWNER_SINGING_SLEEP_RADIUS 7
#define OW_WILD_SPAWNER_SINGING_COOLDOWN_FRAMES 240
#define OW_WILD_SPAWNER_SINGING_GLOBAL_COOLDOWN_FRAMES 1800
#define OW_WILD_SPAWNER_SINGING_SOUND_FRAMES 200
#define OW_WILD_SPAWNER_SINGING_EMOTE_REPEAT_FRAMES 96
#define OW_WILD_SPAWNER_SINGING_EMOTE_COUNT 2
#define OW_WILD_SPAWNER_SINGING_CHANCE_PERCENT 50
#define OW_WILD_SPAWNER_SINGING_SE SEQ_SE_OW_SING
#define OW_WILD_SPAWNER_PLAYFUL_CHILL_HOP_CHANCE_PERCENT 0
#define OW_WILD_SPAWNER_PLAYFUL_ACTIVE_HOP_CHANCE_PERCENT 0
#define OW_WILD_SPAWNER_PLAYFUL_HOPS_ENABLED (OW_WILD_SPAWNER_PLAYFUL_CHILL_HOP_CHANCE_PERCENT > 0 || OW_WILD_SPAWNER_PLAYFUL_ACTIVE_HOP_CHANCE_PERCENT > 0)
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_HOP_MIN_STEPS 4
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_HOP_MAX_STEPS 7
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_HOP_CHANCE_PERCENT 45
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_DOUBLE_HOP_CHANCE_PERCENT 25
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_BUBBLE_CHANCE_PERCENT 45
#define OW_WILD_SPAWNER_PLAYFUL_ORBIT_EMOTE_FRAMES_PER_JUMP 40
#define OW_WILD_SPAWNER_PLAYFUL_NEAR_DISTANCE 2
#define OW_WILD_SPAWNER_PLAYFUL_TARGET_MAX 6
#define OW_WILD_SPAWNER_PLAYFUL_TARGET_DISTANCE_SCORE_MULTIPLIER 16
#define OW_WILD_SPAWNER_PLAYFUL_NO_PROGRESS_SCORE_PENALTY 64
#define OW_WILD_SPAWNER_PLAYFUL_MOVE_AWAY_SCORE_PENALTY 512
#define OW_WILD_SPAWNER_PLAYFUL_PLAYER_PRIORITY_MARGIN 1
#define OW_WILD_SPAWNER_PLAYFUL_RANGE (OW_WILD_SPAWNER_MOVEMENT_RANGE * 2)
#define OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_DISTANCE 5
#define OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_MOVE_DISTANCE 6
#define OW_WILD_SPAWNER_PHANTOM_STALK_CHILL_TELEPORT_MIN_DISTANCE 3
#define OW_WILD_SPAWNER_PHANTOM_STALK_CHILL_TELEPORT_MAX_DISTANCE 6
#define OW_WILD_SPAWNER_PHANTOM_STALK_FLICKER_CHANCE_PERCENT 100
#define OW_WILD_SPAWNER_PHANTOM_STALK_FLICKER_FRAMES 18
#define OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_FLICKER_FRAMES 18
#define OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_MOVE_FRAMES (OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_FLICKER_FRAMES / 2)
#define OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_MOVE_PHASE_FRAMES 2
#define OW_WILD_SPAWNER_PHANTOM_STALK_POST_TELEPORT_COOLDOWN_FRAMES 30
#define OW_WILD_SPAWNER_PHANTOM_STALK_FAIL_COOLDOWN_FRAMES 8
#define OW_WILD_SPAWNER_PHANTOM_STALK_FLICKER_VISIBLE_FRAMES 5
#define OW_WILD_SPAWNER_PHANTOM_STALK_FLICKER_HIDDEN_FRAMES 2
#define OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_VISIBLE_FRAMES 3
#define OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_HIDDEN_FRAMES 2
#define OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_FLICKER_FRAMES \
    (OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_VISIBLE_FRAMES + OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_HIDDEN_FRAMES)
#define OW_WILD_SPAWNER_PHANTOM_STALK_ACTIVE_REAL_FLICKER 0
#define OW_WILD_SPAWNER_PHANTOM_STALK_ALERT_FRAMES 24
#define OW_WILD_SPAWNER_PHANTOM_STALK_RANGE (OW_WILD_SPAWNER_MOVEMENT_RANGE * 2)
#define OW_WILD_SPAWNER_PREVIOUS_TILE_NONE -1
#define OW_WILD_SPAWNER_ONIX_RAM_ALERTNESS 14
#define OW_WILD_SPAWNER_ONIX_RAM_START_SPEED 2
#define OW_WILD_SPAWNER_ONIX_RAM_RANGE 16
#define OW_WILD_SPAWNER_ONIX_RAM_SPEED_UP_TILES 3
#define OW_WILD_SPAWNER_ONIX_RAM_MAX_SPEED OW_WILD_SPAWNER_MOVEMENT_SPEED_4
#define OW_WILD_SPAWNER_ONIX_RAM_CRASH_SE SEQ_SE_DP_WALL_HIT
#define OW_WILD_SPAWNER_ONIX_RAM_STEP_SE SEQ_SE_GS_IWAOTOSHI02
#define OW_WILD_SPAWNER_CANOPY_HOPPER_RANGE 16
#define OW_WILD_SPAWNER_CANOPY_SHIFT_SOUTH_LAND_ANCHORS 1
#define OW_WILD_SPAWNER_CANOPY_SOUTH_LAND_SHIFT_TILES 2
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_VISIBILITY_BASELINE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_SINGLE_JUMP_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_JUMP2_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_CHAINED_JUMP2_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_CHAINED_JUMP2_NO_MIDPOINT_NORMALIZE_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_CHAINED_JUMP2_LOGICAL_MIDPOINT_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_WRAPPED_JUMP2_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_WRAPPED_CHAINED_JUMP2_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_SINGLE_WRAPPER_CHAINED_JUMP2_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_TREE_ANCHOR_PARTNER_PREPPED_INTERNAL_JUMP_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_LONG_JUMP 1
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RENDER_OFFSET 1
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RENDER_FRAMES 15
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RENDER_MAX_SECONDARY_TILES 8
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_SYNC_LOGICAL_SECONDARY 1
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_POST_RESTORE_FINALIZE 1
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RENDER_SETTLE 1
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_POST_LANDING_RENDER_SETTLE 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_POST_LANDING_RENDER_SETTLE_FRAMES 12
#define OW_WILD_SPAWNER_CANOPY_HOPPER_POST_LANDING_RENDER_SETTLE_ENABLED \
    (OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RENDER_SETTLE \
        && OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_POST_LANDING_RENDER_SETTLE \
        && OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_POST_LANDING_RENDER_SETTLE_FRAMES != 0)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_VISIBLE_LEGS 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RAM_PROBE 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RAM_PROBE_MIN_TILES 4
#define OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RAM_PROBE_KEYS \
    (PAD_BUTTON_L | PAD_BUTTON_R)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_MIN_HOP_TILES 3
#define OW_WILD_SPAWNER_CANOPY_HOPPER_AMBUSH_RANGE 8
#define OW_WILD_SPAWNER_CANOPY_HOPPER_MAX_HOP_TILES 8
#define OW_WILD_SPAWNER_MANKEY_HEADBUTT_TREE_TOP_Y_OFFSET 1
#define OW_WILD_SPAWNER_MANKEY_HEADBUTT_TREE_TOP_PRIORITY_BITS 0x00000180
#define OW_WILD_SPAWNER_MANKEY_HEADBUTT_TREE_TOP_DRAW_CALLBACK \
    OverworldWildSpawns_MankeyTreeTopDrawWrapper
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_PROBE_FRAMES 60
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_MASK_2 2
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_MASK_4 4
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_MASK_8 8
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_PROBE_PHASES 4
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LAYER_PROBE_ENABLED 0
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_BUBBLE_PROBE_ENABLED 0
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_BUBBLE_PROBE_FRAMES 90
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_BUBBLE_PROBE_ID OW_WILD_SPAWNER_BUBBLE_ID_EXCLAMATION_MARK
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_EFFECT_MARKER_FRAMES 45
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_EFFECT_MARKER_ID OW_WILD_SPAWNER_BUBBLE_ID_EXCLAMATION_MARK
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_LATE_DRAW_EFFECT_ENABLED 0
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_RENDER_OVERRIDE_SAVE_ENABLED 1
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_PRIORITY_OVERRIDE_ENABLED 0
#define OW_WILD_SPAWNER_MANKEY_TREE_TOP_DRAW_CALLBACK_OVERRIDE_ENABLED 0
#define OW_WILD_SPAWNER_MANKEY_HEADBUTT_TREE_TOP_PATH_MAX_JUMPS 4
#define OW_WILD_SPAWNER_MANKEY_PATH_FAILURE_BASE_COOLDOWN_FRAMES 60
#define OW_WILD_SPAWNER_MANKEY_PATH_FAILURE_MAX_COOLDOWN_FRAMES 240
#define OW_WILD_SPAWNER_MANKEY_PATH_FAILURE_MAX_COUNT 4
#define OW_WILD_SPAWNER_CANOPY_HOPPER_TREE_ALERT_RADIUS 5
#define OW_WILD_SPAWNER_CANOPY_HOPPER_CHASE_JUMPS_MIN 2
#define OW_WILD_SPAWNER_CANOPY_HOPPER_CHASE_JUMPS_MAX 5
#define OW_WILD_SPAWNER_CANOPY_HOPPER_SETUP_DISTANCE_SLACK 3
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PRE_HOP_WAIT_FRAMES 30
#define OW_WILD_SPAWNER_CANOPY_HOPPER_SEGMENT_SETTLE_FRAMES 8
#define OW_WILD_SPAWNER_CANOPY_HOPPER_COOLDOWN_FRAMES 40
#define OW_WILD_SPAWNER_CANOPY_HOPPER_ATTENTIVE_COOLDOWN_FRAMES 0
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_MIN_TILES OW_WILD_SPAWNER_CANOPY_HOPPER_MIN_HOP_TILES
#define OW_WILD_SPAWNER_CANOPY_HOPPER_LONG_JUMP_MAX_TILES OW_WILD_SPAWNER_CANOPY_HOPPER_MAX_HOP_TILES
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_RADIUS (OW_WILD_SPAWNER_CANOPY_HOPPER_RANGE - 1)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_DIAMETER (OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_RADIUS * 2 + 1)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_NODE_COUNT \
    (OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_DIAMETER * OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_DIAMETER)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_WORD_COUNT \
    ((OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_NODE_COUNT + 31) / 32)
#define OW_WILD_SPAWNER_CANOPY_HOPPER_MOVEMENT_LIST_WORDS_PER_SEGMENT 2
#define OW_WILD_SPAWNER_CANOPY_HOPPER_MOVEMENT_LIST_WRAPPER_WORDS 6
#define OW_WILD_SPAWNER_CANOPY_HOPPER_PATH_MAX_STEPS \
    ((OW_WILD_CANOPY_HOP_MOVEMENT_LIST_WORDS - OW_WILD_SPAWNER_CANOPY_HOPPER_MOVEMENT_LIST_WRAPPER_WORDS - 2) / OW_WILD_SPAWNER_CANOPY_HOPPER_MOVEMENT_LIST_WORDS_PER_SEGMENT)
#define OW_WILD_SPAWNER_FX32_ONE (1 << 12)
#define OW_WILD_SPAWNER_TILE_FX32 (OW_WILD_SPAWNER_FX32_ONE * 16)
#define OW_WILD_SPAWNER_TILE_CENTER_FX32 (OW_WILD_SPAWNER_TILE_FX32 / 2)
#define OW_WILD_SPAWNER_TILE_CENTER_COORD_FX32(tile) \
    ((s32)(tile) * OW_WILD_SPAWNER_TILE_FX32 + OW_WILD_SPAWNER_TILE_CENTER_FX32)
#define OW_WILD_SPAWNER_RAM_CRASH_SHAKE_FRAMES 32
#define OW_WILD_SPAWNER_RAM_CRASH_SHAKE_FX32_AMPLITUDE (OW_WILD_SPAWNER_FX32_ONE / 8)
#define OW_WILD_SPAWNER_WAIT_JUMP_SITE_SET_BITS 0x00010004
#define OW_WILD_SPAWNER_WAIT_JUMP_SITE_CLEAR_BITS 0x00100000
#define OW_WILD_SPAWNER_FOLLOWER_CREATE_SET_BITS 0x00002400
#define OW_WILD_SPAWNER_FOLLOWER_CREATE_CLEAR_BITS 0x00000180
#define OW_WILD_SPAWNER_FORCE_BEHAVIOR_TEST_SPECIES 0
#if OW_WILD_SPAWNER_MOVEMENT_DIAGNOSTIC_TRACE \
    || OW_WILD_SPAWNER_CANOPY_HOPPER_DIAGONAL_RAM_PROBE
#define OW_WILD_SPAWNER_DIAGNOSTIC_STORAGE volatile
#else
#define OW_WILD_SPAWNER_DIAGNOSTIC_STORAGE
#endif
#define OW_WILD_SPAWNER_BUBBLE_ID_NONE 0xFF
#define OW_WILD_SPAWNER_SPOT_STATE_CHILL 0
#define OW_WILD_SPAWNER_SPOT_STATE_EMOTING 1
#define OW_WILD_SPAWNER_SPOT_STATE_ACTIVE 2
#define OW_WILD_SPAWNER_SPOT_STATE_TIRED 3
#define OW_WILD_BEHAVIOR_KIND_NONE 0
#define OW_WILD_BEHAVIOR_KIND_IDLE 1
#define OW_WILD_BEHAVIOR_KIND_WANDER 2
#define OW_WILD_BEHAVIOR_KIND_CHASE 3
#define OW_WILD_BEHAVIOR_KIND_FLEE 4
#define OW_WILD_BEHAVIOR_KIND_PLAYFUL 5
#define OW_WILD_BEHAVIOR_KIND_RAM 6
#define OW_WILD_BEHAVIOR_KIND_HEADBUTT_TREE_HOP 7
#define OW_WILD_BEHAVIOR_KIND_ASLEEP 8
#define OW_WILD_BEHAVIOR_KIND_SINGING 9
#define OW_WILD_BEHAVIOR_KIND_TIRED_EMOTE 10
#define OW_WILD_BEHAVIOR_KIND_NO_VISUAL 11
#define OW_WILD_BEHAVIOR_ALERT_STATE_NONE 0
#define OW_WILD_BEHAVIOR_ALERT_STATE_HOP 1
#define OW_WILD_BEHAVIOR_ALERT_STATE_SPEECH 2
#define OW_WILD_BEHAVIOR_ALERT_SPECIAL_NONE 0
#define OW_WILD_BEHAVIOR_ALERT_SPECIAL_CALL_FOR_HELP 1
#define OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_CHILL 0
#define OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_ALERT 1
#define OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_ACTIVE 2
#define OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_TIRED 3
#define OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE 0
#define OW_WILD_BEHAVIOR_BATTLE_TRIGGER_CONTACT 1
#define OW_WILD_BEHAVIOR_BATTLE_TRIGGER_RAM_CRASH 2
#define OW_WILD_BEHAVIOR_JUMP_LEVEL_NONE 0
#define OW_WILD_BEHAVIOR_JUMP_LEVEL_DOWNHILL 1
#define OW_WILD_BEHAVIOR_JUMP_LEVEL_BOTH 2
#define OW_WILD_BEHAVIOR_CLASS_DEFAULT 0
#define OW_WILD_BEHAVIOR_CLASS_SKITTISH 1
#define OW_WILD_BEHAVIOR_CLASS_AGRESSIVE_CHASE 2
#define OW_WILD_BEHAVIOR_CLASS_PLAYFUL 3
#define OW_WILD_BEHAVIOR_CLASS_AGGRESSIVE_RAM 4
#define OW_WILD_BEHAVIOR_CLASS_PHANTOM_STALKER 5
#define OW_WILD_BEHAVIOR_CLASS_SWARM 6
#define OW_WILD_BEHAVIOR_CLASS_CANOPY_HOPPER_2 7
#define OW_WILD_BEHAVIOR_PROFILE_DEFAULT 0
#define OW_WILD_BEHAVIOR_PROFILE_SWARM 3
#define OW_WILD_BEHAVIOR_SPAWN_STATE_APPEAR 0
#define OW_WILD_BEHAVIOR_SPAWN_STATE_RUN_FROM_OFF_SCREEN 1
#define OW_WILD_BEHAVIOR_SPAWN_STATE_HOP_FROM_OFF_SCREEN 2
#define OW_WILD_BEHAVIOR_SPAWN_STATE_APPEAR_HOP 3
#define OW_WILD_BEHAVIOR_BOOL_NO 0
#define OW_WILD_BEHAVIOR_BOOL_YES 1
#define OW_WILD_BEHAVIOR_ALERT_RANGE_NONE 0
#define OW_WILD_BEHAVIOR_ALERT_RANGE_FACING_LINE 1
#define OW_WILD_BEHAVIOR_ALERT_RANGE_FACING_LINE_CLOSE_RADIUS 2
#define OW_WILD_BEHAVIOR_ALERT_RANGE_CARDINAL_LINE 3
#define OW_WILD_BEHAVIOR_ALERT_RANGE_RADIUS 4
#define OW_WILD_BEHAVIOR_ALERT_RANGE_TERRAIN_ONLY 5
#define OW_WILD_BEHAVIOR_ATTENTIVE_ACTION_NONE 0
#define OW_WILD_BEHAVIOR_ATTENTIVE_ACTION_APPROACH 1
#define OW_WILD_BEHAVIOR_ATTENTIVE_ACTION_FLEE 2
#define OW_WILD_BEHAVIOR_ATTENTIVE_ACTION_EMOTE 3
#define OW_WILD_BEHAVIOR_LOCOMOTION_NONE 0
#define OW_WILD_BEHAVIOR_LOCOMOTION_WANDER 1
#define OW_WILD_BEHAVIOR_LOCOMOTION_HOP 2
#define OW_WILD_BEHAVIOR_LOCOMOTION_RUN_FROM_OFF_SCREEN 3
#define OW_WILD_BEHAVIOR_LOCOMOTION_HOP_FROM_OFF_SCREEN 4
#define OW_WILD_BEHAVIOR_LOCOMOTION_RAM 5
#define OW_WILD_BEHAVIOR_LOCOMOTION_PHANTOM_TELEPORT 6
#define OW_WILD_BEHAVIOR_LOCOMOTION_APPEAR_HOP 7
#define OW_WILD_BEHAVIOR_TARGET_NONE 0
#define OW_WILD_BEHAVIOR_TARGET_RANDOM_NEARBY 1
#define OW_WILD_BEHAVIOR_TARGET_TOWARD_PLAYER 2
#define OW_WILD_BEHAVIOR_TARGET_AWAY_FROM_PLAYER 3
#define OW_WILD_BEHAVIOR_TARGET_TREE_TOP 4
#define OW_WILD_BEHAVIOR_TARGET_PLAYFUL_ORBIT 5
#define OW_WILD_BEHAVIOR_TARGET_PLAYER_FRONT 6
#define OW_WILD_BEHAVIOR_TARGET_SWARM 7
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_NONE 0
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_FACING_LINE 1
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_FACING_LINE_CLOSE_RADIUS 2
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_CARDINAL_LINE 3
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_RADIUS 4
#define OW_WILD_BEHAVIOR_ALERT_LOGIC_TERRAIN_ONLY 5
#define OW_WILD_BEHAVIOR_REACTION_NONE 0
#define OW_WILD_BEHAVIOR_REACTION_CONTACT 1
#define OW_WILD_BEHAVIOR_REACTION_FLEE 2
#define OW_WILD_BEHAVIOR_REACTION_CRY 3
#define OW_WILD_BEHAVIOR_REACTION_EMOTE 4
#define OW_WILD_BEHAVIOR_REACTION_TIRED 5
#define OW_WILD_BEHAVIOR_MATCH_ANY_SPECIES SPECIES_NONE
#define OW_WILD_BEHAVIOR_MATCH_ANY_TERRAIN 0xFF
#define OW_WILD_BEHAVIOR_MATCH_ANY_CLASS 0xFF
#define OW_WILD_BEHAVIOR_MATCH_ANY_SHINY 0xFF
#define OW_WILD_BEHAVIOR_MATCH_LEVEL_ANY 0
#define OW_WILD_BEHAVIOR_GROUP_NONE 0
#define OW_WILD_BEHAVIOR_GROUP_BABY (1u << 0)
#define OW_WILD_BEHAVIOR_GROUP_GHOST (1u << 1)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_NORMAL (1u << 2)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_FIGHTING (1u << 3)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_FLYING (1u << 4)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_POISON (1u << 5)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_GROUND (1u << 6)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_ROCK (1u << 7)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_BUG (1u << 8)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_GHOST (1u << 9)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_STEEL (1u << 10)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_FAIRY (1u << 11)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_FIRE (1u << 12)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_WATER (1u << 13)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_GRASS (1u << 14)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_ELECTRIC (1u << 15)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_PSYCHIC (1u << 16)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_ICE (1u << 17)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_DRAGON (1u << 18)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_DARK (1u << 19)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_TYPELESS (1u << 20)
#define OW_WILD_BEHAVIOR_GROUP_TYPE_STELLAR (1u << 21)

// OWBD_VERSION is the persisted blob format version. The overlay entry ABI
// still uses OVERWORLD_WILD_BEHAVIOR_DATA_VERSION.
#define OWBD_VERSION 1
#define OWBD_HEADER_SIZE 52
// Fixed decode capacities mirror the current semantic JSON. The generator
// fails before runtime if these sections grow.
#define OWBD_PROFILE_MAX 8
#define OWBD_CLASS_RULE_MAX 2
#define OWBD_SPECIES_RULE_MAX 110
#define OWBD_OVERRIDE_MAX 2
#define OWBD_SECTION_PROFILES 0
#define OWBD_SECTION_CLASS_RULES 1
#define OWBD_SECTION_SPECIES_RULES 2
#define OWBD_SECTION_OVERRIDES 3
#define OWBD_SECTION_COUNT 4
#define OWBD_CHECKSUM_OFFSET 48

typedef struct OverworldWildBehaviorDataOwbdHeader {
    char magic[4];
    u16 version;
    u16 headerSize;
    u32 totalSize;
    u32 payloadSize;
    u16 counts[OWBD_SECTION_COUNT];
    u32 offsets[OWBD_SECTION_COUNT];
    u16 elementSizes[OWBD_SECTION_COUNT];
    u32 checksum;
} OverworldWildBehaviorDataOwbdHeader;

typedef struct OverworldWildBehaviorDataOwbdRange {
    u32 start;
    u32 end;
} OverworldWildBehaviorDataOwbdRange;

typedef char OverworldWildBehaviorDataOwbdHeaderSize[
    sizeof(OverworldWildBehaviorDataOwbdHeader) == OWBD_HEADER_SIZE ? 1 : -1];

static BOOL sOwbdLoaded;
static OverworldWildBehaviorProfile sOwbdClassProfiles[OWBD_PROFILE_MAX];
static OverworldWildBehaviorClassRule sOwbdClassRules[OWBD_CLASS_RULE_MAX];
static OverworldWildBehaviorSpeciesClassRule sOwbdSpeciesClassRules[OWBD_SPECIES_RULE_MAX];
static OverworldWildBehaviorOverride sOwbdOverrides[OWBD_OVERRIDE_MAX];

extern OverworldWildBehaviorDataOverlayEntry gOverworldWildBehaviorDataOverlayEntry;

static BOOL OverworldWildBehaviorData_IsBehaviorEntryValid(
    const OverworldWildBehaviorDataOverlayEntry *entry)
{
    return entry != NULL
        && entry->magic == OVERWORLD_WILD_BEHAVIOR_DATA_MAGIC
        && entry->version == OVERWORLD_WILD_BEHAVIOR_DATA_VERSION
        && entry->size >= sizeof(OverworldWildBehaviorDataOverlayEntry)
        && entry->classProfiles != NULL
        && entry->classProfileCount > OW_WILD_BEHAVIOR_CLASS_DEFAULT
        && entry->classRules != NULL
        && entry->speciesClassRules != NULL
        && entry->overrides != NULL;
}

static BOOL OverworldWildBehaviorData_BehaviorMatchApplies(
    const OverworldWildBehaviorContext *context,
    const OverworldWildBehaviorMatch *match)
{
    if (context == NULL || match == NULL) {
        return FALSE;
    }

    if (match->species != OW_WILD_BEHAVIOR_MATCH_ANY_SPECIES
        && match->species != context->species) {
        return FALSE;
    }
    if (match->groupMask != OW_WILD_BEHAVIOR_GROUP_NONE
        && (context->groupFlags & match->groupMask) == 0) {
        return FALSE;
    }
    if (match->terrain != OW_WILD_BEHAVIOR_MATCH_ANY_TERRAIN
        && match->terrain != context->terrain) {
        return FALSE;
    }
    if (match->minLevel != OW_WILD_BEHAVIOR_MATCH_LEVEL_ANY
        && context->level < match->minLevel) {
        return FALSE;
    }
    if (match->maxLevel != OW_WILD_BEHAVIOR_MATCH_LEVEL_ANY
        && context->level > match->maxLevel) {
        return FALSE;
    }
    if (match->shiny != OW_WILD_BEHAVIOR_MATCH_ANY_SHINY
        && match->shiny != context->shiny) {
        return FALSE;
    }
    if (match->behaviorClass != OW_WILD_BEHAVIOR_MATCH_ANY_CLASS
        && match->behaviorClass != context->behaviorClass) {
        return FALSE;
    }

    return TRUE;
}

#define OW_WILD_PROFILE_OFFSET(field) ((u8)(u32)&(((OverworldWildBehaviorProfile *)0)->field))

static const u8 sOverworldWildBehaviorOverrideFieldOffsets[] = {
    OW_WILD_PROFILE_OFFSET(chillState),
    OW_WILD_PROFILE_OFFSET(alertState),
    OW_WILD_PROFILE_OFFSET(alertEmote),
    OW_WILD_PROFILE_OFFSET(alertness),
    OW_WILD_PROFILE_OFFSET(attentiveState),
    OW_WILD_PROFILE_OFFSET(stamina),
    OW_WILD_PROFILE_OFFSET(tiredState),
    OW_WILD_PROFILE_OFFSET(restTime),
    OW_WILD_PROFILE_OFFSET(chillSpeed),
    OW_WILD_PROFILE_OFFSET(attentiveSpeed),
    OW_WILD_PROFILE_OFFSET(range),
    OW_WILD_PROFILE_OFFSET(jumpLevel),
    OW_WILD_PROFILE_OFFSET(profileId),
    OW_WILD_PROFILE_OFFSET(spawnState),
    OW_WILD_PROFILE_OFFSET(chillAction),
    OW_WILD_PROFILE_OFFSET(alertRange),
    OW_WILD_PROFILE_OFFSET(tiredSpeed),
    OW_WILD_PROFILE_OFFSET(targetSelector),
    OW_WILD_PROFILE_OFFSET(movementStyle),
    OW_WILD_PROFILE_OFFSET(chillCooldown),
    OW_WILD_PROFILE_OFFSET(attentiveCooldown),
    OW_WILD_PROFILE_OFFSET(alertChance),
    OW_WILD_PROFILE_OFFSET(alertTime),
    OW_WILD_PROFILE_OFFSET(spawnDestination),
    OW_WILD_PROFILE_OFFSET(chillBattle),
    OW_WILD_PROFILE_OFFSET(alertBattle),
    OW_WILD_PROFILE_OFFSET(attentiveBattle),
    OW_WILD_PROFILE_OFFSET(tiredBattle),
    OW_WILD_PROFILE_OFFSET(specialAction),
    OW_WILD_PROFILE_OFFSET(hopAllowNonCardinal),
    OW_WILD_PROFILE_OFFSET(hopMinDistance),
    OW_WILD_PROFILE_OFFSET(hopMaxDistance),
    OW_WILD_PROFILE_OFFSET(hopPause),
    OW_WILD_PROFILE_OFFSET(teleportTime),
    OW_WILD_PROFILE_OFFSET(teleportPause),
    OW_WILD_PROFILE_OFFSET(alertSpecialAction),
    OW_WILD_PROFILE_OFFSET(alertCallSpawnAmount),
    OW_WILD_PROFILE_OFFSET(spawnDestinationMinDistance),
    OW_WILD_PROFILE_OFFSET(spawnDestinationMaxDistance),
    OW_WILD_PROFILE_OFFSET(ramAccelerationSteps),
    OW_WILD_PROFILE_OFFSET(ramMaxSpeed),
    OW_WILD_PROFILE_OFFSET(chillAllowedTile),
    OW_WILD_PROFILE_OFFSET(attentiveAllowedTile),
    OW_WILD_PROFILE_OFFSET(tiredAllowedTile),
    OW_WILD_PROFILE_OFFSET(chillAllowedTile2),
    OW_WILD_PROFILE_OFFSET(attentiveAllowedTile2),
    OW_WILD_PROFILE_OFFSET(tiredAllowedTile2),
    OW_WILD_PROFILE_OFFSET(chillTarget),
    OW_WILD_PROFILE_OFFSET(attentiveHopAllowNonCardinal),
    OW_WILD_PROFILE_OFFSET(attentiveHopMinDistance),
    OW_WILD_PROFILE_OFFSET(attentiveHopMaxDistance),
    OW_WILD_PROFILE_OFFSET(attentiveHopPause),
    OW_WILD_PROFILE_OFFSET(attentiveTeleportTime),
    OW_WILD_PROFILE_OFFSET(attentiveTeleportPause),
    OW_WILD_PROFILE_OFFSET(attentiveRamAccelerationSteps),
    OW_WILD_PROFILE_OFFSET(attentiveRamMaxSpeed),
    OW_WILD_PROFILE_OFFSET(tiredHopAllowNonCardinal),
    OW_WILD_PROFILE_OFFSET(tiredHopMinDistance),
    OW_WILD_PROFILE_OFFSET(tiredHopMaxDistance),
    OW_WILD_PROFILE_OFFSET(tiredHopPause),
    OW_WILD_PROFILE_OFFSET(tiredTeleportTime),
    OW_WILD_PROFILE_OFFSET(tiredTeleportPause),
    OW_WILD_PROFILE_OFFSET(tiredRamAccelerationSteps),
    OW_WILD_PROFILE_OFFSET(tiredRamMaxSpeed),
    OW_WILD_PROFILE_OFFSET(alertCallSpawnState),
};

#undef OW_WILD_PROFILE_OFFSET

static void OverworldWildBehaviorData_ApplyBehaviorOverrideMask(
    OverworldWildBehaviorProfile *profile,
    const OverworldWildBehaviorProfile *overrideProfile,
    u32 mask,
    u8 fieldIndex)
{
    u8 *profileBytes = (u8 *)profile;
    const u8 *overrideBytes = (const u8 *)overrideProfile;

    while (mask != 0 && fieldIndex < NELEMS(sOverworldWildBehaviorOverrideFieldOffsets)) {
        if (mask & 1u) {
            u8 offset = sOverworldWildBehaviorOverrideFieldOffsets[fieldIndex];
            profileBytes[offset] = overrideBytes[offset];
        }
        mask >>= 1;
        fieldIndex++;
    }
}

static void OverworldWildBehaviorData_ApplyBehaviorOverride(
    OverworldWildBehaviorProfile *profile,
    const OverworldWildBehaviorOverride *override)
{
    if (profile == NULL || override == NULL) {
        return;
    }

    OverworldWildBehaviorData_ApplyBehaviorOverrideMask(profile, &override->profile, override->mask, 0);
    OverworldWildBehaviorData_ApplyBehaviorOverrideMask(profile, &override->profile, override->mask2, 32);
    OverworldWildBehaviorData_ApplyBehaviorOverrideMask(profile, &override->profile, override->mask3, 48);
}

static BOOL OverworldWildBehaviorData_IsValidBehaviorKind(u8 behavior)
{
    return behavior <= OW_WILD_BEHAVIOR_KIND_NO_VISUAL;
}

static BOOL OverworldWildBehaviorData_IsValidMovementStyle(u8 movementStyle)
{
    return movementStyle <= OW_WILD_BEHAVIOR_LOCOMOTION_APPEAR_HOP;
}

static BOOL OverworldWildBehaviorData_IsValidAlertSpecialAction(u8 action)
{
    return action <= OW_WILD_BEHAVIOR_ALERT_SPECIAL_CALL_FOR_HELP;
}

static BOOL OverworldWildBehaviorData_ProfileUsesAlertCallForHelp(
    const OverworldWildBehaviorProfile *profile)
{
    return profile != NULL
        && profile->alertSpecialAction == OW_WILD_BEHAVIOR_ALERT_SPECIAL_CALL_FOR_HELP;
}

static u8 OverworldWildBehaviorData_GetAlertCallSpawnAmount(
    const OverworldWildBehaviorProfile *profile)
{
    if (!OverworldWildBehaviorData_ProfileUsesAlertCallForHelp(profile)) {
        return 0;
    }
    if (profile->alertCallSpawnAmount == 0) {
        return 1;
    }
    if (profile->alertCallSpawnAmount > OW_WILD_SPAWNER_SWARM_MAX_EXTRA_SPAWNS) {
        return OW_WILD_SPAWNER_SWARM_MAX_EXTRA_SPAWNS;
    }
    return profile->alertCallSpawnAmount;
}

static u8 OverworldWildBehaviorData_NormalizePhantomTeleportMoveFrames(u8 teleportTime)
{
    if (teleportTime == 0) {
        return OW_WILD_SPAWNER_PHANTOM_STALK_TELEPORT_MOVE_FRAMES;
    }

    return teleportTime;
}

static u8 OverworldWildBehaviorData_NormalizePhantomTeleportPauseFrames(u8 teleportPause)
{
    if (teleportPause == 0) {
        return OW_WILD_SPAWNER_PHANTOM_STALK_POST_TELEPORT_COOLDOWN_FRAMES;
    }

    return teleportPause;
}

static BOOL OverworldWildBehaviorData_BehaviorUsesAsleep(u8 behavior)
{
    return behavior == OW_WILD_BEHAVIOR_KIND_ASLEEP;
}

static void OverworldWildBehaviorData_NormalizeBehaviorProfile(
    OverworldWildBehaviorProfile *profile)
{
    if (profile == NULL) {
        return;
    }

    if (profile->attentiveSpeed == 0) {
        profile->attentiveSpeed = OW_WILD_SPAWNER_MOVEMENT_SPEED_DEFAULT;
    }
    if (profile->chillSpeed == 0) {
        profile->chillSpeed = OW_WILD_SPAWNER_MOVEMENT_SPEED_DEFAULT;
    }
    if (profile->tiredSpeed == 0) {
        profile->tiredSpeed = profile->chillSpeed;
    }
    if (!OverworldWildBehaviorData_IsValidBehaviorKind(profile->chillState)) {
        profile->chillState = OW_WILD_BEHAVIOR_KIND_IDLE;
    }
    if (!OverworldWildBehaviorData_IsValidMovementStyle(profile->chillAction)) {
        profile->chillAction = OW_WILD_BEHAVIOR_LOCOMOTION_NONE;
    }
    if (!OverworldWildBehaviorData_IsValidMovementStyle(profile->movementStyle)) {
        profile->movementStyle = OW_WILD_BEHAVIOR_LOCOMOTION_NONE;
    }
    if (!OverworldWildBehaviorData_IsValidMovementStyle(profile->specialAction)) {
        profile->specialAction = OW_WILD_BEHAVIOR_LOCOMOTION_NONE;
    }
    if (!OverworldWildBehaviorData_IsValidAlertSpecialAction(profile->alertSpecialAction)) {
        profile->alertSpecialAction = OW_WILD_BEHAVIOR_ALERT_SPECIAL_NONE;
    }
    profile->alertCallSpawnAmount = OverworldWildBehaviorData_GetAlertCallSpawnAmount(profile);
    if (profile->alertCallSpawnState > OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_TIRED) {
        profile->alertCallSpawnState = OW_WILD_BEHAVIOR_ALERT_CALL_SPAWN_STATE_ACTIVE;
    }
    if (profile->hopAllowNonCardinal > OW_WILD_BEHAVIOR_BOOL_YES) {
        profile->hopAllowNonCardinal = OW_WILD_BEHAVIOR_BOOL_YES;
    }
    if (profile->hopMinDistance == 0) {
        profile->hopMinDistance = 1;
    }
    if (profile->hopMaxDistance == 0) {
        profile->hopMaxDistance = profile->hopMinDistance;
    }
    if (profile->hopMaxDistance < profile->hopMinDistance) {
        profile->hopMaxDistance = profile->hopMinDistance;
    }
    if (profile->ramAccelerationSteps > OW_WILD_SPAWNER_MOVEMENT_RANGE) {
        profile->ramAccelerationSteps = OW_WILD_SPAWNER_MOVEMENT_RANGE;
    }
    if (profile->ramMaxSpeed > OW_WILD_SPAWNER_MOVEMENT_SPEED_4) {
        profile->ramMaxSpeed = OW_WILD_SPAWNER_MOVEMENT_SPEED_4;
    }
    profile->teleportTime =
        OverworldWildBehaviorData_NormalizePhantomTeleportMoveFrames(profile->teleportTime);
    profile->teleportPause =
        OverworldWildBehaviorData_NormalizePhantomTeleportPauseFrames(profile->teleportPause);
    if (profile->chillTarget > OW_WILD_BEHAVIOR_TARGET_SWARM) {
        profile->chillTarget = OW_WILD_BEHAVIOR_TARGET_NONE;
    }
    if (profile->targetSelector > OW_WILD_BEHAVIOR_TARGET_SWARM) {
        profile->targetSelector = OW_WILD_BEHAVIOR_TARGET_NONE;
    }
    if (!OverworldWildBehaviorData_IsValidBehaviorKind(profile->attentiveState)) {
        profile->attentiveState = OW_WILD_BEHAVIOR_KIND_NONE;
    }
    if (!OverworldWildBehaviorData_IsValidBehaviorKind(profile->tiredState)) {
        profile->tiredState = OW_WILD_BEHAVIOR_KIND_NONE;
    }
    if (OverworldWildBehaviorData_BehaviorUsesAsleep(profile->chillState)) {
        profile->tiredState = OW_WILD_BEHAVIOR_KIND_ASLEEP;
        profile->stamina = 1;
        profile->restTime = 0;
        profile->alertness = 0;
        profile->alertChance = 0;
    } else if (OverworldWildBehaviorData_BehaviorUsesAsleep(profile->tiredState)) {
        profile->stamina = 1;
        profile->restTime = 0;
    }
    if ((profile->attentiveState != OW_WILD_BEHAVIOR_KIND_NONE
            || profile->targetSelector != OW_WILD_BEHAVIOR_TARGET_NONE
            || profile->movementStyle != OW_WILD_BEHAVIOR_LOCOMOTION_NONE
            || profile->attentiveBattle != OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE)
        && profile->tiredState != OW_WILD_BEHAVIOR_KIND_NONE
        && profile->stamina == 0) {
        profile->stamina = 1;
    }
    if (profile->tiredState != OW_WILD_BEHAVIOR_KIND_NONE
        && !OverworldWildBehaviorData_BehaviorUsesAsleep(profile->tiredState)
        && profile->restTime == 0) {
        profile->restTime = 1;
    }
    if (profile->range == 0) {
        profile->range = OW_WILD_SPAWNER_MOVEMENT_RANGE;
    }
    if (profile->jumpLevel > OW_WILD_BEHAVIOR_JUMP_LEVEL_BOTH) {
        profile->jumpLevel = OW_WILD_BEHAVIOR_JUMP_LEVEL_BOTH;
    }
    if (profile->spawnState > OW_WILD_BEHAVIOR_SPAWN_STATE_APPEAR_HOP) {
        profile->spawnState = OW_WILD_BEHAVIOR_SPAWN_STATE_APPEAR;
    }
    if (profile->alertState > OW_WILD_BEHAVIOR_ALERT_STATE_SPEECH) {
        profile->alertState = OW_WILD_BEHAVIOR_ALERT_STATE_NONE;
    }
    if (profile->alertEmote > OW_WILD_SPAWNER_BUBBLE_ID_SLEEP
        && profile->alertEmote != OW_WILD_SPAWNER_BUBBLE_ID_NONE) {
        profile->alertEmote = OW_WILD_SPAWNER_BUBBLE_ID_NONE;
    }
    if (profile->alertRange > OW_WILD_BEHAVIOR_ALERT_RANGE_TERRAIN_ONLY) {
        profile->alertRange = OW_WILD_BEHAVIOR_ALERT_RANGE_NONE;
    }
    if (profile->spawnDestination > OW_WILD_SPAWN_DESTINATION_NEXT_TO_PLAYER) {
        profile->spawnDestination = OW_WILD_SPAWN_DESTINATION_POOL;
    }
    if (profile->spawnDestinationMinDistance == 0) {
        profile->spawnDestinationMinDistance = OW_WILD_PLAYER_RELATIVE_SPAWN_MIN_DISTANCE;
    }
    if (profile->spawnDestinationMinDistance > OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE) {
        profile->spawnDestinationMinDistance = OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE;
    }
    if (profile->spawnDestinationMaxDistance == 0) {
        profile->spawnDestinationMaxDistance = OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE;
    }
    if (profile->spawnDestinationMaxDistance > OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE) {
        profile->spawnDestinationMaxDistance = OW_WILD_PLAYER_RELATIVE_SPAWN_MAX_DISTANCE;
    }
    if (profile->spawnDestinationMaxDistance < profile->spawnDestinationMinDistance) {
        profile->spawnDestinationMaxDistance = profile->spawnDestinationMinDistance;
    }
    if (profile->chillBattle > OW_WILD_BEHAVIOR_BATTLE_TRIGGER_RAM_CRASH) {
        profile->chillBattle = OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE;
    }
    if (profile->alertBattle > OW_WILD_BEHAVIOR_BATTLE_TRIGGER_RAM_CRASH) {
        profile->alertBattle = OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE;
    }
    if (profile->attentiveBattle > OW_WILD_BEHAVIOR_BATTLE_TRIGGER_RAM_CRASH) {
        profile->attentiveBattle = OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE;
    }
    if (profile->tiredBattle > OW_WILD_BEHAVIOR_BATTLE_TRIGGER_RAM_CRASH) {
        profile->tiredBattle = OW_WILD_BEHAVIOR_BATTLE_TRIGGER_NONE;
    }
}

static BOOL OverworldWildBehaviorData_ResolveBehaviorClass(
    const OverworldWildBehaviorDataOverlayEntry *entry,
    const OverworldWildBehaviorContext *context,
    u8 *behaviorClassOut)
{
    u8 behaviorClass = OW_WILD_BEHAVIOR_CLASS_DEFAULT;
    int i;

    if (behaviorClassOut == NULL) {
        return FALSE;
    }
    *behaviorClassOut = behaviorClass;
    if (context == NULL || !OverworldWildBehaviorData_IsBehaviorEntryValid(entry)) {
        return FALSE;
    }

    for (i = 0; i < entry->classRuleCount; i++) {
        if (OverworldWildBehaviorData_BehaviorMatchApplies(context, &entry->classRules[i].match)) {
            behaviorClass = entry->classRules[i].behaviorClass;
        }
    }
    for (i = 0; i < entry->speciesClassRuleCount; i++) {
        if (entry->speciesClassRules[i].species == context->species) {
            behaviorClass = entry->speciesClassRules[i].behaviorClass;
        }
    }

    if (behaviorClass >= entry->classProfileCount) {
        behaviorClass = OW_WILD_BEHAVIOR_CLASS_DEFAULT;
    }
    *behaviorClassOut = behaviorClass;
    return TRUE;
}

static BOOL OverworldWildBehaviorData_ResolveBehaviorProfile(
    const OverworldWildBehaviorDataOverlayEntry *entry,
    const OverworldWildBehaviorContext *context,
    const OverworldWildBehaviorProfile *fallbackProfile,
    OverworldWildBehaviorProfile *profileOut)
{
    u8 behaviorClass = OW_WILD_BEHAVIOR_CLASS_DEFAULT;
    int i;

    if (profileOut == NULL) {
        return FALSE;
    }
    if (fallbackProfile != NULL) {
        *profileOut = *fallbackProfile;
    }
    if (context != NULL) {
        behaviorClass = context->behaviorClass;
    }
    if (!OverworldWildBehaviorData_IsBehaviorEntryValid(entry)) {
        return FALSE;
    }

    if (behaviorClass >= entry->classProfileCount) {
        behaviorClass = OW_WILD_BEHAVIOR_CLASS_DEFAULT;
    }
    *profileOut = entry->classProfiles[behaviorClass];

    if (context != NULL) {
        for (i = 0; i < entry->overrideCount; i++) {
            if (OverworldWildBehaviorData_BehaviorMatchApplies(
                    context,
                    &entry->overrides[i].match)) {
                OverworldWildBehaviorData_ApplyBehaviorOverride(profileOut, &entry->overrides[i]);
            }
        }
    }

    OverworldWildBehaviorData_NormalizeBehaviorProfile(profileOut);
    return TRUE;
}

static u32 OverworldWildBehaviorData_Crc32(const u8 *data, u32 size)
{
    u32 crc = 0xFFFFFFFF;
    u32 i;
    u32 bit;

    for (i = 0; i < size; i++) {
        u8 value = (i >= OWBD_CHECKSUM_OFFSET && i < OWBD_CHECKSUM_OFFSET + sizeof(u32))
            ? 0
            : data[i];
        crc ^= value;
        for (bit = 0; bit < 8; bit++) {
            if (crc & 1) {
                crc = (crc >> 1) ^ 0xEDB88320;
            } else {
                crc >>= 1;
            }
        }
    }

    return crc ^ 0xFFFFFFFF;
}

static BOOL OverworldWildBehaviorData_CheckSection(
    const OverworldWildBehaviorDataOwbdHeader *header,
    u32 section,
    u32 expectedElementSize,
    u32 maxCount,
    u32 blobSize,
    OverworldWildBehaviorDataOwbdRange *rangeOut)
{
    u32 count = header->counts[section];
    u32 offset = header->offsets[section];
    u32 byteCount;
    u32 end;

    if (count == 0) {
        if (offset != 0 || header->elementSizes[section] != 0) {
            return FALSE;
        }
        if (rangeOut != NULL) {
            rangeOut->start = 0;
            rangeOut->end = 0;
        }
        return TRUE;
    }

    if (count > maxCount
        || header->elementSizes[section] != expectedElementSize
        || offset < OWBD_HEADER_SIZE
        || (offset & 3) != 0) {
        return FALSE;
    }

    byteCount = count * expectedElementSize;
    end = offset + byteCount;
    if (end < offset || end > blobSize) {
        return FALSE;
    }

    if (rangeOut != NULL) {
        rangeOut->start = offset;
        rangeOut->end = end;
    }
    return TRUE;
}

static BOOL OverworldWildBehaviorData_RangesDoNotOverlap(
    OverworldWildBehaviorDataOwbdRange *ranges,
    u32 count)
{
    u32 i;
    u32 j;

    for (i = 1; i < count; i++) {
        OverworldWildBehaviorDataOwbdRange current = ranges[i];
        j = i;
        while (j > 0 && ranges[j - 1].start > current.start) {
            ranges[j] = ranges[j - 1];
            j--;
        }
        ranges[j] = current;
    }

    for (i = 1; i < count; i++) {
        if (ranges[i].start < ranges[i - 1].end) {
            return FALSE;
        }
    }
    return TRUE;
}

static BOOL OverworldWildBehaviorData_ValidateOwbd(
    const u8 *blob,
    u32 blobSize,
    const OverworldWildBehaviorDataOwbdHeader **headerOut)
{
    const OverworldWildBehaviorDataOwbdHeader *header;
    OverworldWildBehaviorDataOwbdRange ranges[OWBD_SECTION_COUNT];
    OverworldWildBehaviorDataOwbdRange nonEmptyRanges[OWBD_SECTION_COUNT];
    u32 nonEmptyRangeCount = 0;
    u32 i;

    if (blob == NULL || blobSize < OWBD_HEADER_SIZE || headerOut == NULL) {
        return FALSE;
    }

    header = (const OverworldWildBehaviorDataOwbdHeader *)blob;
    if (header->magic[0] != 'O'
        || header->magic[1] != 'W'
        || header->magic[2] != 'B'
        || header->magic[3] != 'D'
        || header->version != OWBD_VERSION
        || header->headerSize != OWBD_HEADER_SIZE
        || header->totalSize != blobSize
        || header->payloadSize != blobSize - OWBD_HEADER_SIZE
        || header->checksum != OverworldWildBehaviorData_Crc32(blob, blobSize)) {
        return FALSE;
    }

    if (!OverworldWildBehaviorData_CheckSection(
            header,
            OWBD_SECTION_PROFILES,
            sizeof(OverworldWildBehaviorProfile),
            OWBD_PROFILE_MAX,
            blobSize,
            &ranges[OWBD_SECTION_PROFILES])
        || !OverworldWildBehaviorData_CheckSection(
            header,
            OWBD_SECTION_CLASS_RULES,
            sizeof(OverworldWildBehaviorClassRule),
            OWBD_CLASS_RULE_MAX,
            blobSize,
            &ranges[OWBD_SECTION_CLASS_RULES])
        || !OverworldWildBehaviorData_CheckSection(
            header,
            OWBD_SECTION_SPECIES_RULES,
            sizeof(OverworldWildBehaviorSpeciesClassRule),
            OWBD_SPECIES_RULE_MAX,
            blobSize,
            &ranges[OWBD_SECTION_SPECIES_RULES])
        || !OverworldWildBehaviorData_CheckSection(
            header,
            OWBD_SECTION_OVERRIDES,
            sizeof(OverworldWildBehaviorOverride),
            OWBD_OVERRIDE_MAX,
            blobSize,
            &ranges[OWBD_SECTION_OVERRIDES])) {
        return FALSE;
    }

    for (i = 0; i < OWBD_SECTION_COUNT; i++) {
        if (header->counts[i] != 0) {
            nonEmptyRanges[nonEmptyRangeCount++] = ranges[i];
        }
    }
    if (!OverworldWildBehaviorData_RangesDoNotOverlap(nonEmptyRanges, nonEmptyRangeCount)) {
        return FALSE;
    }

    *headerOut = header;
    return TRUE;
}

static void OverworldWildBehaviorData_CopySection(
    void *dest,
    const u8 *blob,
    u32 offset,
    u32 count,
    u32 elementSize)
{
    if (count != 0) {
        memcpy(dest, (void *)(blob + offset), count * elementSize);
    }
}

static BOOL OverworldWildBehaviorData_DecodeOwbd(const u8 *blob, u32 blobSize)
{
    const OverworldWildBehaviorDataOwbdHeader *header;

    if (!OverworldWildBehaviorData_ValidateOwbd(blob, blobSize, &header)
        || header->counts[OWBD_SECTION_PROFILES] <= OW_WILD_BEHAVIOR_CLASS_DEFAULT) {
        return FALSE;
    }

    OverworldWildBehaviorData_CopySection(
        sOwbdClassProfiles,
        blob,
        header->offsets[OWBD_SECTION_PROFILES],
        header->counts[OWBD_SECTION_PROFILES],
        sizeof(OverworldWildBehaviorProfile));
    OverworldWildBehaviorData_CopySection(
        sOwbdClassRules,
        blob,
        header->offsets[OWBD_SECTION_CLASS_RULES],
        header->counts[OWBD_SECTION_CLASS_RULES],
        sizeof(OverworldWildBehaviorClassRule));
    OverworldWildBehaviorData_CopySection(
        sOwbdSpeciesClassRules,
        blob,
        header->offsets[OWBD_SECTION_SPECIES_RULES],
        header->counts[OWBD_SECTION_SPECIES_RULES],
        sizeof(OverworldWildBehaviorSpeciesClassRule));
    OverworldWildBehaviorData_CopySection(
        sOwbdOverrides,
        blob,
        header->offsets[OWBD_SECTION_OVERRIDES],
        header->counts[OWBD_SECTION_OVERRIDES],
        sizeof(OverworldWildBehaviorOverride));

    gOverworldWildBehaviorDataOverlayEntry.classProfiles = sOwbdClassProfiles;
    gOverworldWildBehaviorDataOverlayEntry.classProfileCount =
        header->counts[OWBD_SECTION_PROFILES];
    gOverworldWildBehaviorDataOverlayEntry.classRules = sOwbdClassRules;
    gOverworldWildBehaviorDataOverlayEntry.classRuleCount =
        header->counts[OWBD_SECTION_CLASS_RULES];
    gOverworldWildBehaviorDataOverlayEntry.speciesClassRules = sOwbdSpeciesClassRules;
    gOverworldWildBehaviorDataOverlayEntry.speciesClassRuleCount =
        header->counts[OWBD_SECTION_SPECIES_RULES];
    gOverworldWildBehaviorDataOverlayEntry.overrides = sOwbdOverrides;
    gOverworldWildBehaviorDataOverlayEntry.overrideCount =
        header->counts[OWBD_SECTION_OVERRIDES];
    sOwbdLoaded = TRUE;
    return TRUE;
}

static BOOL OverworldWildBehaviorData_LoadFromOwbd(void)
{
    void *narc;
    u8 *blob;
    u32 blobSize;
    BOOL loaded;

    if (sOwbdLoaded) {
        return TRUE;
    }

    narc = NARC_ctor(ARC_CODE_ADDONS, HEAPID_WORLD);
    if (narc == NULL) {
        return FALSE;
    }

    blobSize = NARC_GetMemberSize(narc, CODE_ADDON_OVERWORLD_WILD_BEHAVIOR_DATA);
    if (blobSize < OWBD_HEADER_SIZE) {
        NARC_dtor(narc);
        return FALSE;
    }

    blob = sys_AllocMemory(HEAPID_WORLD, blobSize);
    if (blob == NULL) {
        NARC_dtor(narc);
        return FALSE;
    }

    NARC_ReadWholeMember(narc, CODE_ADDON_OVERWORLD_WILD_BEHAVIOR_DATA, blob);
    NARC_dtor(narc);
    loaded = OverworldWildBehaviorData_DecodeOwbd(blob, blobSize);
    sys_FreeMemoryEz(blob);
    return loaded;
}

OverworldWildBehaviorDataOverlayEntry gOverworldWildBehaviorDataOverlayEntry
    __attribute__((section(".overworld_wild_behavior_data_entry"), used)) = {
    OVERWORLD_WILD_BEHAVIOR_DATA_MAGIC,
    OVERWORLD_WILD_BEHAVIOR_DATA_VERSION,
    sizeof(OverworldWildBehaviorDataOverlayEntry),
    NULL,
    0,
    NULL,
    0,
    NULL,
    0,
    NULL,
    0,
    sOverworldWildEncounterAreaMapIds,
    sOverworldWildEncounterAreaDataIds,
    OW_WILD_ENCOUNTER_AREA_COUNT,
    OverworldWildBehaviorData_LoadFromOwbd,
    OverworldWildBehaviorData_ResolveBehaviorClass,
    OverworldWildBehaviorData_ResolveBehaviorProfile,
};

#endif // IMPLEMENT_OVERWORLD_WILD_SPAWNS
