#include "../../include/overworld_actor_system_internal.h"
#include "../../include/overworld_wild_behavior_data.h"

/*
 * Task 6 has a hard resident boundary at +0xE40. Keep the complete Teleport
 * policy below that boundary so the role reducer's growth reserve stays free.
 * The field adapter supplies only classification; this code owns candidate
 * order, acceptance, timing, facing, visibility, pause, and the final plan.
 */
__asm__(
    ".syntax unified\n"
    ".arch armv5te\n"
    ".thumb\n"
    ".section .overworld_actor_teleport_planner_code,\"ax\",%progbits\n"
    ".align 2\n"
    ".thumb_set .Ltp_direction_from_delta, 0x023BF68C\n"
    ".thumb_set .Ltp_delta_x, 0x023BF59C\n"
    ".thumb_set .Ltp_delta_y, 0x023BF5BE\n"
    ".thumb_func\n"
    ".type OverworldActorTeleportPlanner_PlanImpl,%function\n"
    "OverworldActorTeleportPlanner_PlanImpl:\n"
    "push {r4-r7, lr}\n"
    "sub sp, #32\n"
    "mov r5, sp\n"
    "movs r7, r0\n"
    "ldr r6, [r7, #32]\n"
    "ldr r0, [r6, #0]\n"
    "cmp r0, #0\n"
    "beq .Ltp_profile_local\n"
    "ldr r0, [r6, #8]\n"
    "cmp r0, #0\n"
    "beq .Ltp_profile_local\n"
    "ldrb r0, [r6, #28]\n"
    "cmp r0, #2\n"
    "bhi .Ltp_profile_local\n"
    "cmp r0, #1\n"
    "bne 2f\n"
    "ldr r1, [r6, #4]\n"
    "cmp r1, #0\n"
    "beq .Ltp_profile_local\n"
    "ldrb r1, [r6, #29]\n"
    "cmp r1, #0\n"
    "beq .Ltp_profile_local\n"
    "cmp r1, #8\n"
    "bhi .Ltp_profile_local\n"
    "b 2f\n"
    ".Ltp_profile_local:\n"
    "movs r0, #8\n"
    "b .Ltp_return\n"
    "2:\n"
    "movs r1, #255\n"
    "strb r1, [r7, #7]\n"
    "movs r4, #0\n"
    "strb r4, [r7, #5]\n"
    "movs r1, #12\n"
    "strb r1, [r7, #6]\n"
    "cmp r0, #0\n"
    "bne .Ltp_candidate\n"
    "movs r2, #24\n"
    "ldrsh r0, [r6, r2]\n"
    "movs r2, #12\n"
    "ldrsh r1, [r7, r2]\n"
    "subs r0, r0, r1\n"
    "str r0, [sp, #16]\n"
    "asrs r1, r0, #31\n"
    "eors r0, r1\n"
    "subs r0, r0, r1\n"
    "str r0, [sp, #24]\n"
    "movs r2, #26\n"
    "ldrsh r0, [r6, r2]\n"
    "movs r2, #14\n"
    "ldrsh r1, [r7, r2]\n"
    "subs r0, r0, r1\n"
    "str r0, [sp, #20]\n"
    "asrs r1, r0, #31\n"
    "eors r0, r1\n"
    "subs r0, r0, r1\n"
    "str r0, [sp, #28]\n"
    "ldr r1, [sp, #24]\n"
    "cmp r1, r0\n"
    "bhs 3f\n"
    "movs r1, r0\n"
    "3:\n"
    "cmp r1, #0\n"
    "bne 16f\n"
    "b .Ltp_done\n"
    "16:\n"
    "cmp r1, #6\n"
    "bls 4f\n"
    "movs r1, #6\n"
    "4:\n"
    "strb r1, [r5, #13]\n"
    "ldr r0, [sp, #16]\n"
    "ldr r1, [sp, #20]\n"
    "bl .Ltp_direction_from_delta\n"
    "strb r0, [r7, #9]\n"
    ".Ltp_candidate:\n"
    "ldrb r0, [r6, #28]\n"
    "cmp r0, #0\n"
    "beq .Ltp_adjacent\n"
    "cmp r0, #1\n"
    "beq .Ltp_directional\n"
    "cmp r4, #16\n"
    "bhs .Ltp_done_middle\n"
    "movs r2, r4\n"
    "lsrs r2, r2, #2\n"
    "ldr r1, [r6, #20]\n"
    "adds r1, r1, r2\n"
    "movs r0, #3\n"
    "ands r1, r0\n"
    "adds r1, #3\n"
    "movs r2, r4\n"
    "ands r2, r0\n"
    "ldr r0, [r6, #16]\n"
    "adds r0, r0, r2\n"
    "movs r2, #3\n"
    "ands r0, r2\n"
    "adr r2, .Ltp_chill_directions\n"
    "ldrb r0, [r2, r0]\n"
    "b .Ltp_build\n"
    ".Ltp_directional:\n"
    "movs r0, r4\n"
    "movs r1, #6\n"
    "bl __aeabi_uidivmod\n"
    "ldrb r2, [r6, #29]\n"
    "cmp r0, r2\n"
    "bhs .Ltp_done_middle\n"
    "ldr r2, [r6, #4]\n"
    "ldrb r0, [r2, r0]\n"
    "movs r2, #6\n"
    "subs r1, r2, r1\n"
    "b .Ltp_build\n"
    ".Ltp_adjacent:\n"
    "ldrb r1, [r5, #13]\n"
    "cmp r4, r1\n"
    "bhs .Ltp_done_middle\n"
    "subs r1, r1, r4\n"
    "ldrb r0, [r7, #9]\n"
    "b .Ltp_build\n"
    ".Ltp_done_middle:\n"
    "b .Ltp_done\n"
    ".Ltp_build:\n"
    "movs r2, #0\n"
    "strh r2, [r5, #8]\n"
    "subs r2, #1\n"
    "strh r2, [r5, #14]\n"
    "ldr r2, [r7, #16]\n"
    "str r2, [r5, #4]\n"
    "strb r0, [r5, #10]\n"
    "strb r1, [r5, #11]\n"
    "strb r0, [r5, #12]\n"
    "cmp r0, #8\n"
    "blo 9f\n"
    "movs r2, #32\n"
    "strh r2, [r5, #8]\n"
    "b .Ltp_classified\n"
    "9:\n"
    "ldrb r2, [r6, #28]\n"
    "cmp r2, #0\n"
    "bne .Ltp_cardinal_target\n"
    "ldr r2, [sp, #24]\n"
    "cmp r2, r1\n"
    "bls 10f\n"
    "movs r2, r1\n"
    "10:\n"
    "ldr r3, [sp, #16]\n"
    "cmp r3, #0\n"
    "bge 11f\n"
    "negs r2, r2\n"
    "11:\n"
    "ldrh r3, [r7, #12]\n"
    "adds r3, r3, r2\n"
    "strh r3, [r5, #0]\n"
    "ldr r2, [sp, #28]\n"
    "cmp r2, r1\n"
    "bls 12f\n"
    "movs r2, r1\n"
    "12:\n"
    "ldr r3, [sp, #20]\n"
    "cmp r3, #0\n"
    "bge 13f\n"
    "negs r2, r2\n"
    "13:\n"
    "ldrh r3, [r7, #14]\n"
    "adds r3, r3, r2\n"
    "strh r3, [r5, #2]\n"
    "b .Ltp_classify\n"
    ".Ltp_cardinal_target:\n"
    "bl .Ltp_delta_x\n"
    "ldrb r1, [r5, #11]\n"
    "muls r0, r1\n"
    "ldrh r3, [r7, #12]\n"
    "adds r0, r0, r3\n"
    "strh r0, [r5, #0]\n"
    "ldrb r0, [r5, #10]\n"
    "bl .Ltp_delta_y\n"
    "ldrb r1, [r5, #11]\n"
    "muls r0, r1\n"
    "ldrh r3, [r7, #14]\n"
    "adds r0, r0, r3\n"
    "strh r0, [r5, #2]\n"
    ".Ltp_classify:\n"
    "ldr r3, [r6, #8]\n"
    "ldr r0, [r6, #12]\n"
    "movs r1, r5\n"
    "blx r3\n"
    ".Ltp_classified:\n"
    "adds r4, #1\n"
    "strb r4, [r7, #5]\n"
    "ldrh r0, [r5, #8]\n"
    "ldrb r1, [r6, #31]\n"
    "bl OverworldActorTeleportPlanner_CandidateDecision\n"
    "movs r3, r0\n"
    "cmp r3, #0\n"
    "beq .Ltp_accept\n"
    "blt .Ltp_stop\n"
    ".Ltp_continue:\n"
    "strb r3, [r7, #6]\n"
    "b .Ltp_candidate\n"
    ".Ltp_accept:\n"
    "subs r0, r4, #1\n"
    "strb r0, [r7, #7]\n"
    "movs r0, r7\n"
    "movs r1, r5\n"
    "bl OverworldActorTeleportPlanner_FillPlan\n"
    "movs r0, #0\n"
    "b .Ltp_return\n"
    ".Ltp_done:\n"
    "ldrb r0, [r7, #6]\n"
    "b .Ltp_return\n"
    ".Ltp_stop:\n"
    "negs r0, r3\n"
    ".Ltp_return:\n"
    "add sp, #32\n"
    "pop {r4-r7, pc}\n"
    ".align 2\n"
    ".Ltp_chill_directions:\n"
    ".byte 0, 3, 1, 2\n"
    ".size OverworldActorTeleportPlanner_PlanImpl,.-OverworldActorTeleportPlanner_PlanImpl\n"

    ".section .overworld_actor_teleport_planner_tail,\"ax\",%progbits\n"
    ".align 2\n"
    ".thumb_func\n"
    ".type OverworldActorTeleportPlanner_CandidateDecision,%function\n"
    "OverworldActorTeleportPlanner_CandidateDecision:\n"
    "cmp r0, #0\n"
    "beq 20f\n"
    "movs r2, #1\n"
    "movs r3, #64\n"
    "tst r0, r3\n"
    "beq 24f\n"
    "negs r2, r2\n"
    "b 21f\n"
    "24:\n"
    "movs r2, #7\n"
    "movs r3, #32\n"
    "tst r0, r3\n"
    "bne 21f\n"
    "movs r2, #3\n"
    "movs r3, #2\n"
    "22:\n"
    "tst r0, r3\n"
    "bne 21f\n"
    "adds r2, #1\n"
    "lsls r3, r3, #1\n"
    "cmp r3, #32\n"
    "bne 22b\n"
    "movs r2, #2\n"
    "21:\n"
    "cmp r2, #6\n"
    "bne 25f\n"
    "lsrs r1, r1, #1\n"
    "bcc 25f\n"
    "negs r2, r2\n"
    "25:\n"
    "movs r0, r2\n"
    "20:\n"
    "bx lr\n"
    ".size OverworldActorTeleportPlanner_CandidateDecision,.-OverworldActorTeleportPlanner_CandidateDecision\n"

    ".align 2\n"
    ".thumb_func\n"
    ".type OverworldActorTeleportPlanner_FillPlan,%function\n"
    "OverworldActorTeleportPlanner_FillPlan:\n"
    "push {r4-r7, lr}\n"
    "movs r4, r0\n"
    "movs r5, r1\n"
    "ldr r6, [r4, #32]\n"
    "ldr r7, [r4, #28]\n"
    "movs r0, r7\n"
    "movs r1, #0\n"
    "movs r2, #40\n"
    "bl memset\n"
    "movs r0, #1\n"
    "strh r0, [r7, #0]\n"
    "movs r0, #3\n"
    "strb r0, [r7, #2]\n"
    "ldrb r0, [r5, #12]\n"
    "strb r0, [r7, #3]\n"
    "ldrh r0, [r4, #10]\n"
    "strh r0, [r7, #4]\n"
    "ldr r0, [r4, #12]\n"
    "str r0, [r7, #8]\n"
    "ldr r0, [r5, #0]\n"
    "str r0, [r7, #12]\n"
    "ldr r0, [r4, #16]\n"
    "str r0, [r7, #16]\n"
    "ldr r0, [r5, #4]\n"
    "str r0, [r7, #20]\n"
    "ldr r2, [r6, #0]\n"
    "ldrb r0, [r2, #23]\n"
    "ldrb r3, [r2, #12]\n"
    "cmp r3, #10\n"
    "blo 23f\n"
    "ldrb r1, [r5, #11]\n"
    "muls r0, r1\n"
    "23:\n"
    "strh r0, [r7, #24]\n"
    "ldrh r0, [r5, #10]\n"
    "strh r0, [r7, #28]\n"
    "movs r0, #1\n"
    "ands r3, r0\n"
    "movs r0, #2\n"
    "subs r0, r0, r3\n"
    "movs r1, #32\n"
    "adds r1, r7, r1\n"
    "strb r0, [r1, #1]\n"
    "ldrb r0, [r2, #24]\n"
    "strb r0, [r1, #2]\n"
    "ldrb r0, [r6, #30]\n"
    "strb r0, [r1, #3]\n"
    "ldrh r0, [r5, #14]\n"
    "strh r0, [r4, #36]\n"
    "pop {r4-r7, pc}\n"
    ".size OverworldActorTeleportPlanner_FillPlan,.-OverworldActorTeleportPlanner_FillPlan\n"
    ".section .overworld_actor_teleport_planner,\"ax\",%progbits\n"
    ".align 2\n"
    ".global OverworldActorTeleportPlanner_Plan\n"
    ".thumb_func\n"
    ".type OverworldActorTeleportPlanner_Plan,%function\n"
    "OverworldActorTeleportPlanner_Plan:\n"
    "ldr r3, 1f\n"
    "bx r3\n"
    ".align 2\n"
    "1: .word OverworldActorTeleportPlanner_PlanImpl + 1\n"
    ".size OverworldActorTeleportPlanner_Plan,.-OverworldActorTeleportPlanner_Plan\n"
);
