"""Shared point reader, using host memory only; no native core or ROM run.

The fixed slot tables below are reviewed against the four branches of stock
ov01_021F635C, not generated by the reader's coordinate formula. Optional local
reference checks pin that assembly and compile its real public matrix types.
"""
import hashlib
import inspect
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from tools.overworld import devtools_engine as engine

ROOT = Path(__file__).resolve().parents[2]
GLOBAL = 0x02001000
CONFIG = 0x02002000
FIELD = 0x02100000
MATRIX = 0x02101000
MANAGER = 0x02103000
TABLE = 0x02104000
CHUNKS = (0x02200000, 0x02201000, 0x02202000, 0x02203000)
FULL = 0x02210000


class Memory:
    def __init__(self):
        self.data, self.reads = {}, []
        self.after_read = None

    def region(self, address, size):
        self.data.update((address + i, 0) for i in range(size))

    def put(self, address, value, size=4):
        self.data.update((address + i, byte) for i, byte in enumerate(value.to_bytes(size, "little")))

    def read(self, _emu, address, size=4):
        self.reads.append((address, size))
        result = int.from_bytes(bytes(self.data[address + i] for i in range(size)), "little")
        if self.after_read:
            self.after_read(address, size)
        return result


class Fixture:
    def __init__(self, current=6, slot=0, width=5, height=4):
        self.memory = m = Memory()
        for address, size in ((GLOBAL, 4), (CONFIG, 8), (FIELD, 0x100), (MATRIX, 0xFC0),
                              (MANAGER, 0x110), (TABLE, 8), (FULL, 226 + 16 * 2048)):
            m.region(address, size)
        for pointer in CHUNKS:
            m.region(pointer, 0xA74)
        m.put(GLOBAL, FIELD)
        m.put(FIELD + 0x2C, MANAGER)
        m.put(FIELD + 0x30, MATRIX)
        m.put(FIELD + 0x60, TABLE)
        m.put(TABLE + 4, 0x020547D9)
        m.put(MATRIX, width, 1)
        m.put(MATRIX + 1, height, 1)
        m.put(MATRIX + 2, 7, 1)
        m.put(MATRIX + 4, height, 1)
        m.put(MATRIX + 5, width, 1)
        m.put(MANAGER + 0xC0, MATRIX)
        m.put(MANAGER + 0xC4, width)
        m.put(MANAGER + 0xC8, height)
        m.put(MANAGER + 0xCC, width * 32)
        m.put(MANAGER + 0xA4, current)
        m.put(MANAGER + 0xAC, slot, 1)
        for index in range(width * height):
            m.put(MATRIX + 6 + index * 2, 33 + index, 2)
            m.put(MATRIX + 0x644 + index, 2 + index, 1)
            m.put(MATRIX + 0x964 + index * 2, 100 + index, 2)
        for i, pointer in enumerate(CHUNKS):
            m.put(MANAGER + 0x90 + i * 4, pointer)
            m.put(pointer + 0x860, 0xFFFFFFFF)
            m.put(pointer + 0x864, 1)

    def cell(self, index, slot, attribute=0x9502, local=(9, 17), width=5):
        m, pointer = self.memory, CHUNKS[slot]
        m.put(pointer + 0x860, index)
        m.put(pointer + (local[1] * 32 + local[0]) * 2, attribute, 2)
        return (index % width) * 32 + local[0], (index // width) * 32 + local[1]

    def read(self, x, y):
        with patch.object(engine, "G_FIELD_SYS_PTR", GLOBAL), patch.object(engine, "unsigned", self.memory.read):
            return engine.loaded_terrain_cell(None, x, y)

    def full_store(self, count=4, block=3):
        m = self.memory
        m.put(FIELD + 0x5C, FULL); m.put(TABLE + 4, 0x02054825)
        m.put(FIELD + 0x74, CONFIG)
        # Actual UnkStruct_020FC5CC: reader mode bits8..11, full-store
        # enabled bits16..19, loaded block count bits24..31.
        m.put(CONFIG, (count << 24) | (1 << 16) | (1 << 8))
        m.put(FULL + 6, block, 1)
        address = FULL + 226 + (block * 1024 + 17 * 32 + 9) * 2
        m.put(address, 0x0010, 2)
        return address


class TerrainPointTests(unittest.TestCase):
    def test_each_stock_current_slot_resolves_all_four_blocks(self):
        # Current matrix index 6 is (1,1). Slot number is its position in the
        # loaded 2x2 window, not a modulo of world coordinates.
        expected = ({6: 0, 7: 1, 11: 2, 12: 3},
                    {5: 0, 6: 1, 10: 2, 11: 3},
                    {1: 0, 2: 1, 6: 2, 7: 3},
                    {0: 0, 1: 1, 5: 2, 6: 3})
        for current_slot, mapping in enumerate(expected):
            for index, slot in mapping.items():
                with self.subTest(currentSlot=current_slot, index=index, slot=slot):
                    fixture = Fixture(slot=current_slot)
                    x, y = fixture.cell(index, slot)
                    cell = fixture.read(x, y)
                    self.assertIsNotNone(cell, "stock-loaded adjacent block was reported unknown")
                    self.assertEqual((cell["block"], cell["matrix_index"], cell["attribute"]), (slot, index, 0x9502))

    def test_edges_do_not_wrap_to_another_row_or_clamp_unloaded_cells(self):
        for current, slot, wanted in ((4, 0, 5), (5, 1, 4), (0, 3, 1), (19, 0, 14), (6, 0, 13)):
            with self.subTest(current=current, slot=slot, wanted=wanted):
                fixture = Fixture(current=current, slot=slot)
                x, y = fixture.cell(wanted, 1)
                self.assertIsNone(fixture.read(x, y))

    def test_same_current_slot_rejects_old_or_loading_chunk(self):
        for fault in ("stale-index", "uninitialized", "not-loaded", "invalid-loaded", "queued-first", "queued-second", "deferred", "slot-invalidated"):
            with self.subTest(fault=fault):
                f = Fixture(); x, y = f.cell(6, 0)
                if fault == "stale-index": f.memory.put(CHUNKS[0] + 0x860, 7)
                elif fault == "uninitialized": f.memory.put(CHUNKS[0] + 0x860, 0xFFFFFFFF)
                elif fault == "not-loaded": f.memory.put(CHUNKS[0] + 0x864, 0)
                elif fault == "invalid-loaded": f.memory.put(CHUNKS[0] + 0x864, 2)
                elif fault == "slot-invalidated": f.memory.put(MANAGER + 0x80, 1)
                elif fault == "deferred":
                    f.memory.put(MANAGER + 0x6C, 1); f.memory.put(MANAGER + 0x64, CHUNKS[0])
                else:
                    offset = 0 if fault == "queued-first" else 0x30
                    f.memory.put(MANAGER + offset + 0x2C, 1)
                    f.memory.put(MANAGER + offset + 4, CHUNKS[0])
                self.assertIsNone(f.read(x, y), "old bytes are not loaded-terrain evidence")

    def test_unrelated_loading_chunk_does_not_hide_current_ready_cell(self):
        f = Fixture(); x, y = f.cell(6, 0)
        f.memory.put(MANAGER + 0x2C, 1)
        f.memory.put(MANAGER + 4, CHUNKS[1])
        f.memory.put(MANAGER + 8, CHUNKS[2])
        self.assertIsNotNone(f.read(x, y))

    def test_local_tile_edges_use_the_selected_block_without_aliasing(self):
        for index, slot in ((6, 0), (7, 1), (11, 2), (12, 3)):
            for local in ((0, 0), (31, 0), (0, 31), (31, 31)):
                with self.subTest(index=index, local=local):
                    f = Fixture(); x, y = f.cell(index, slot, attribute=index, local=local)
                    self.assertEqual(f.read(x, y)["attribute"], index)

    def test_duplicate_chunk_pointer_is_not_a_unique_loaded_slot(self):
        f = Fixture(); x, y = f.cell(6, 0)
        f.memory.put(MANAGER + 0x94, CHUNKS[0])
        self.assertIsNone(f.read(x, y))

    def test_context_bounds_and_pointer_mismatch_remain_unknown(self):
        edits = ((GLOBAL, 0, 4), (FIELD + 0x30, 0, 4), (FIELD + 0x2C, 0, 4),
                 (MANAGER + 0xC0, MATRIX + 4, 4), (MANAGER + 0xC4, 4, 4),
                 (MANAGER + 0xC8, 3, 4), (MANAGER + 0xCC, 161, 4),
                 (MANAGER + 0xA4, 20, 4), (MANAGER + 0xAC, 4, 1),
                 (MANAGER + 0x90, 0, 4), (MANAGER + 0x90, CHUNKS[0] + 1, 4),
                 (MANAGER + 0x90, 0x023FFFF0, 4), (MATRIX + 0x964 + 12, 0xFFFF, 2),
                 (MATRIX, 255, 1), (MATRIX + 4, 3, 1), (TABLE + 4, 0x02054825, 4))
        for address, value, size in edits:
            with self.subTest(address=hex(address), value=value):
                f = Fixture(); x, y = f.cell(6, 0)
                f.memory.put(address, value, size)
                self.assertIsNone(f.read(x, y))
        for x, y in ((-1, 0), (0, -1), (160, 0), (0, 128), (1.5, 2), (True, 2)):
            with self.subTest(x=x, y=y):
                self.assertIsNone(Fixture().read(x, y))

    def test_provenance_preserves_word_address_and_does_not_claim_elevation(self):
        f = Fixture(); x, y = f.cell(6, 0)
        cell = f.read(x, y)
        self.assertEqual((cell["behavior"], cell["collision"], cell["terrain_class"]), (2, True, 21))
        p = cell["provenance"]
        self.assertEqual(p["fieldPointer"], FIELD)
        self.assertEqual(p["landManagerPointer"], MANAGER)
        self.assertEqual(p["mapMatrixPointer"], MATRIX)
        self.assertEqual(p["matrixId"], 7)
        self.assertEqual(p["landDataId"], 106)
        self.assertEqual(p["mapHeaderId"], 39)
        self.assertEqual(p["matrixAltitude"], 8)
        self.assertEqual(p["chunkMatrixIndex"], 6)
        self.assertEqual(p["attributeAddress"], CHUNKS[0] + (17 * 32 + 9) * 2)
        self.assertEqual(p["rawWord"], cell["attribute"])
        self.assertEqual(p["landDataIdentity"], "current-map-matrix")
        self.assertNotIn("elevation", cell)
        self.assertNotIn("height", cell)
        self.assertLess(len(f.memory.reads), 90, "one point must not scan a terrain grid")

    def test_mid_read_owner_or_chunk_change_is_not_a_coherent_receipt(self):
        for address, changed in ((GLOBAL, FIELD + 4), (MANAGER + 0x90, CHUNKS[1]),
                                 (CHUNKS[0] + 0x860, 7), (MATRIX + 0x964 + 12, 999)):
            with self.subTest(address=hex(address)):
                f = Fixture(); x, y = f.cell(6, 0)
                target = CHUNKS[0] + (17 * 32 + 9) * 2
                def mutate(at, _size):
                    if at == target: f.memory.put(address, changed, 2 if address == MATRIX + 0x964 + 12 else 4)
                f.memory.after_read = mutate
                self.assertIsNone(f.read(x, y))

    def test_full_store_keeps_block_mapping_and_rejects_invalid_block(self):
        f = Fixture(); m = f.memory
        address = f.full_store(count=4, block=3)
        cell = f.read(41, 49)
        self.assertEqual((cell["block"], cell["attribute"], cell["collision"]), (3, 16, False))
        self.assertEqual(cell["provenance"]["attributeAddress"], address)
        self.assertEqual(cell["provenance"]["fieldConfigPointer"], CONFIG)
        self.assertEqual(cell["provenance"]["fieldConfigWord"], 0x04010100)
        self.assertEqual(cell["provenance"]["loadedBlockCount"], 4)
        self.assertIsNone(cell["provenance"]["landManagerPointer"])
        m.put(FULL + 6, 16, 1)
        self.assertIsNone(f.read(41, 49))

    def test_full_store_capacity_is_not_a_loaded_block_count(self):
        f = Fixture(); address = f.full_store(count=1, block=3)
        self.assertIsNone(f.read(41, 49), "capacity16 does not prove block3 was loaded")
        self.assertNotIn((address, 2), f.memory.reads, "unloaded block bytes must not become evidence")

    def test_full_store_requires_its_active_bounded_config(self):
        for fault in ("count-zero", "count-over-capacity", "missing", "unaligned", "disabled", "wrong-mode"):
            with self.subTest(fault=fault):
                f = Fixture(); f.full_store(count=1, block=0)
                if fault == "count-zero": f.memory.put(CONFIG, 0x00010100)
                elif fault == "count-over-capacity": f.memory.put(CONFIG, 0x11010100)
                elif fault == "missing": f.memory.put(FIELD + 0x74, 0)
                elif fault == "unaligned": f.memory.put(FIELD + 0x74, CONFIG + 1)
                elif fault == "disabled": f.memory.put(CONFIG, 0x01000100)
                elif fault == "wrong-mode": f.memory.put(CONFIG, 0x01010000)
                self.assertIsNone(f.read(41, 49))
        f = Fixture(); f.full_store(count=1, block=0)
        self.assertEqual(f.read(41, 49)["provenance"]["loadedBlockCount"], 1)

    def test_full_store_config_must_stay_current_during_the_read(self):
        for address, changed in ((FIELD + 0x74, CONFIG + 4), (CONFIG, 0x01010100)):
            with self.subTest(address=hex(address)):
                f = Fixture(); target = f.full_store(count=4, block=3)
                def mutate(at, _size):
                    if at == target: f.memory.put(address, changed)
                f.memory.after_read = mutate
                self.assertIsNone(f.read(41, 49))

    def test_known_bad_reader_changes_are_detected_by_the_same_fixture(self):
        original = inspect.getsource(engine.loaded_terrain_cell)
        controls = (
            ("current-block-only", "if dx not in (0, 1) or dy not in (0, 1):",
             "if matrix_index != current or dx not in (0, 1) or dy not in (0, 1):"),
            ("wrong-slot", "block = dx + 2 * dy", "block = (dx + 2 * dy) ^ 1"),
            ("accept-stale-tag", "chunk_index != matrix_index or loaded != 1",
             "False or loaded != 1"),
            ("accept-unloaded", "chunk_index != matrix_index or loaded != 1",
             "chunk_index != matrix_index or False"),
            ("accept-queued-reuse", "for base in (0, 0x30):", "for base in ():"),
            ("capacity-as-loaded", "if block >= block_count:", "if block >= TERRAIN_MAX_BLOCKS:"),
        )
        for name, old, new in controls:
            with self.subTest(control=name):
                self.assertEqual(original.count(old), 1, "mutation seam changed")
                namespace = dict(vars(engine))
                # The actual reader body is compiled in isolation. Each case
                # changes one guard; the fixture and expected result stay fixed.
                exec(compile(original.replace(old, new), "<terrain-reader-control>", "exec"), namespace)
                f = Fixture()
                if name in ("current-block-only", "wrong-slot"):
                    x, y = f.cell(7, 1)
                    expected_loaded = True
                elif name == "capacity-as-loaded":
                    f.full_store(count=1, block=3)
                    x, y, expected_loaded = 41, 49, False
                else:
                    x, y = f.cell(6, 0); expected_loaded = False
                    if name == "accept-stale-tag": f.memory.put(CHUNKS[0] + 0x860, 7)
                    elif name == "accept-unloaded": f.memory.put(CHUNKS[0] + 0x864, 0)
                    else:
                        f.memory.put(MANAGER + 0x2C, 1)
                        f.memory.put(MANAGER + 4, CHUNKS[0])
                namespace.update(G_FIELD_SYS_PTR=GLOBAL, unsigned=f.memory.read)
                actual_loaded = namespace["loaded_terrain_cell"](None, x, y) is not None
                self.assertNotEqual(actual_loaded, expected_loaded, "known-bad reader escaped its control")


class StockTerrainAnchors(unittest.TestCase):
    def test_real_arm_field_config_pointer_and_loaded_count_layout(self):
        directory = ROOT / ".codex-reference/pokeheartgold/include"
        cc, objcopy = shutil.which("arm-none-eabi-gcc"), shutil.which("arm-none-eabi-objcopy")
        if not cc or not objcopy or not (directory / "field_system.h").is_file():
            self.skipTest("ARM tools or optional read-only stock headers unavailable")
        field = (directory / "field_system.h").read_text()
        # Preserve the actual stock prefix through the config pointer; opaque
        # pointer pointees do not need their unrelated definitions for layout.
        prefix = re.search(r"struct FieldSystem \{.*?\*unk74;", field, re.S).group() + "\n};\n"
        opaque = set(re.findall(r"^\s*(\w+)\s+\*\w+", prefix, re.M)) - {"void"}
        source = "#include <stddef.h>\ntypedef unsigned int u32; typedef unsigned char u8; typedef int BOOL;\n"
        source += "\n".join("typedef void " + name + ";" for name in sorted(opaque)) + "\n" + prefix
        source += re.search(r"struct UnkStruct_020FC5CC \{.*?\n\};",
                            (directory / "script.h").read_text(), re.S).group() + "\n"
        source += '_Static_assert(sizeof(void *)==4,"actual ARM pointer width");\n'
        source += '_Static_assert(offsetof(struct FieldSystem, unk74)==0x74,"field config pointer");\n'
        source += ('const struct UnkStruct_020FC5CC observed __attribute__((section(".terrain_config_layout"))) = '
                   '{ .unk0_08=1, .unk0_10=1, .unk0_18=4 };\n')
        with tempfile.TemporaryDirectory(prefix="terrain-config-layout-") as temp:
            path, obj, binary = Path(temp) / "layout.c", Path(temp) / "layout.o", Path(temp) / "layout.bin"
            path.write_text(source)
            compiled = subprocess.run([cc, "-std=c11", "-Werror", "-c", str(path), "-o", str(obj)],
                                      capture_output=True, text=True)
            self.assertEqual(compiled.returncode, 0, compiled.stderr)
            extracted = subprocess.run([objcopy, "-O", "binary", "--only-section=.terrain_config_layout",
                                        str(obj), str(binary)], capture_output=True, text=True)
            self.assertEqual(extracted.returncode, 0, extracted.stderr)
            self.assertEqual(binary.read_bytes()[:4], bytes((0, 1, 1, 4)),
                             "reader mode, enabled bit and loaded count must follow the real ARM bitfields")

    def test_reviewed_stock_mapping_and_load_lifecycle_are_unchanged(self):
        path = ROOT / ".codex-reference/pokeheartgold/asm/overlay_01_021F4704.s"
        if not path.is_file(): self.skipTest("optional read-only stock reference unavailable")
        source = path.read_text()
        # Hashes pin the reviewed independent assembly behind the literal slot
        # tables and loader-state guards; they do not certify current ROM code.
        expected = {
            "ov01_021F4728": "152f17f477087f9df19aad2799cafbcf60162bc60aa439e76b9800ab2a20f1dd",
            "ov01_021F635C": "4635ecac7b6506ae2e5915bf42834a8f1753e1731aa439b614466078075b174c",
            "ov01_021F654C": "254bb35e49e364449f6bd71593469334e01c867a877feac8be4599977b65e80e",
            "ov01_021F65E4": "ae6669e9766eb9a4485d5b25e4eb673ffbd0ebc49264608751774aac6ce319ea",
            "ov01_021F5038": "ee68978dc3c6f8fd84d5835f60f335a484106962171c18e9f16918a2e2da8c5f",
            "ov01_021F4C6C": "6f22078b862bfc18d0787c84a88162c12b0dd2f4e85659ba9cacad59ea050a9d",
            "ov01_021F5568": "a58bfa8fb42d005a3801bd0873ce2ec0169faaf7e6a42f1ed72d9c4bdea8b1de",
        }
        for name, digest in expected.items():
            body = re.search(r"\tthumb_func_start " + name + r"\n.*?\tthumb_func_end " + name, source, re.S).group()
            self.assertEqual(hashlib.sha256(body.encode()).hexdigest(), digest, name + " needs source re-review")

    def test_real_matrix_and_full_terrain_types_have_the_expected_layout(self):
        directory = ROOT / ".codex-reference/pokeheartgold/include"
        cc = shutil.which("cc")
        if not cc or not (directory / "map_matrix.h").is_file():
            self.skipTest("host compiler or optional stock headers unavailable")
        source = "#include <stddef.h>\n#include <stdint.h>\ntypedef uint8_t u8; typedef uint16_t u16;\n"
        for filename in ("map_matrix.h", "terrain_attributes.h"):
            raw = (directory / filename).read_text()
            source += "\n".join(line for line in raw.splitlines() if line.startswith("#define ") and len(line.split()) > 2) + "\n"
            source += "\n".join(re.findall(r"typedef struct \w+ \{.*?\} \w+;", raw, re.S)) + "\n"
        source += '_Static_assert(offsetof(MAPMATRIX, data.headers)==6,"headers");\n'
        source += '_Static_assert(offsetof(MAPMATRIX, data.altitudes)==0x644,"altitudes");\n'
        source += '_Static_assert(offsetof(MAPMATRIX, data.maps.models)==0x964,"models");\n'
        source += '_Static_assert(offsetof(TerrainAttributes, terrainAttributes)==226,"full attributes");\n'
        with tempfile.TemporaryDirectory(prefix="terrain-types-") as temp:
            path = Path(temp) / "layout.c"; path.write_text(source)
            result = subprocess.run([cc, "-std=c11", "-Werror", "-fsyntax-only", str(path)], capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stderr)


if __name__ == "__main__": unittest.main()
