.nds
.thumb

OverworldMount_PlayerMoveControl equ 0x023BB620
OverworldMount_FieldInputProcess equ 0x023BB6E0
OverworldMount_PlayCrashSound equ 0x023BB740

/*
 * Each retail site contains exactly one Thumb BL and retains its original
 * epilogue/caller frame. The resident wrappers ultimately call the stock
 * implementation after applying mount policy.
 */
.open "base/arm9.bin", 0x02000000

.org 0x0203E1F0
.area 4
    bl OverworldMount_PlayerMoveControl
.endarea

.org 0x0203E260
.area 4
    bl OverworldMount_PlayerMoveControl
.endarea

.org 0x0203E2E4
.area 4
    bl OverworldMount_PlayerMoveControl
.endarea

/* FieldInput_Process checks warps before forced movement. Filter the
 * synthetic step/end signals generated by mounted custom Hop ownership. */
.org 0x0203E270
.area 4
    bl OverworldMount_FieldInputProcess
.endarea

/* Normal walking has two collision branches which play the wall-hit SE. */
.org 0x0205D532
.area 4
    bl OverworldMount_PlayCrashSound
.endarea

.org 0x0205D5C2
.area 4
    bl OverworldMount_PlayCrashSound
.endarea

.close
