cmake_minimum_required(VERSION 3.16)
project(ow_melonds LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(BUILD_QT_SDL OFF CACHE BOOL "" FORCE)
set(ENABLE_JIT OFF CACHE BOOL "" FORCE)
set(ENABLE_OGLRENDERER OFF CACHE BOOL "" FORCE)
set(ENABLE_GDBSTUB OFF CACHE BOOL "" FORCE)
set(ENABLE_LTO_RELEASE OFF CACHE BOOL "" FORCE)
add_subdirectory("${MELONDS_SOURCE}" melonDS)
target_include_directories(core PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
add_library(ow_melonds SHARED bridge.cpp platform.cpp)
target_link_libraries(ow_melonds PRIVATE core)
set_target_properties(ow_melonds PROPERTIES CXX_VISIBILITY_PRESET default)
add_executable(ow_melonds_core_test core_test.cpp platform.cpp)
target_link_libraries(ow_melonds_core_test PRIVATE core)
