#!/usr/bin/env python3

import re
import sys
from pathlib import Path


SYMBOLS = [
    "OverworldWildSpawns_LoadOverworldModelResource",
]


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_armips_symbols.py <rom_gen.ld> <output>")

    linker_text = Path(sys.argv[1]).read_text()
    output = Path(sys.argv[2])
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = ["// Generated by scripts/generate_armips_symbols.py."]
    for symbol in SYMBOLS:
        match = re.search(rf"^{re.escape(symbol)}\s*=\s*(0x[0-9a-fA-F]+);", linker_text, re.MULTILINE)
        if match is None:
            raise SystemExit(f"missing symbol: {symbol}")
        lines.append(f"{symbol.lower()} equ {match.group(1)}")
    lines.append("")

    contents = "\n".join(lines)
    if output.exists() and output.read_text() == contents:
        return
    output.write_text(contents)


if __name__ == "__main__":
    main()
