#!/usr/bin/env python3
"""Run the fail-closed overworld host proof tests from any working directory."""

from __future__ import annotations

import argparse
import sys
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))


TESTS = (
        "tools.overworld.test_host_verification",
        "tools.overworld.test_actor_facade_commands",
        "scripts.test_verify_overworld_behavior_resolver_control",
        "tools.overworld.test_evidence_store",
        "tools.overworld.test_proof_identity",
        "tools.overworld.test_proof_inputs",
        "tools.overworld.test_cadence_diagnostics",
        "tools.overworld.test_spawn_destination_scan",
        "tools.overworld.test_follower_refill_reads",
        "tools.overworld.test_spawn_refill_budget",
        "tools.overworld.test_field_party_move_query",
        "tools.overworld.test_devtools_cpu_work",
        "tools.overworld.test_proof_reuse",
        "tools.overworld.test_proof_adapters",
        "tools.overworld.test_runtime_migration_supersession",
        "tools.overworld.test_runtime_migration_coverage",
        "tools.overworld.test_scenario_claims",
        "tools.overworld.test_progress",
        "tools.overworld.test_imported_proof_source_audit",
        "tools.overworld.test_normal_play_observer",
        "tools.overworld.test_chain_action_lifecycle",
        "tools.overworld.test_devtools_chain_retry_control",
        "tools.overworld.test_devtools_chain_retry_measurement",
        "tools.overworld.test_devtools_chain_retry_contract",
        "tools.overworld.test_chain_retry_proof",
        "tools.overworld.test_walk_policy_candidate_rejection",
        "tools.overworld.test_turn_skid_path_planning",
        "tools.overworld.test_chain_reposition_facing",
        "tools.overworld.test_runtime_fixture",
        "tools.overworld.test_wild_packaging_abi",
        "tools.overworld.test_devtools",
        "tools.overworld.test_devtools_records",
        "tools.overworld.test_devtools_cli",
        "tools.overworld.test_devtools_http",
        "tools.overworld.test_devtools_catalog",
        "tools.overworld.test_devtools_runtime",
        "tools.overworld.test_devtools_party_receipts",
        "tools.overworld.test_devtools_trace",
        "tools.overworld.test_devtools_trace_publication",
        "tools.overworld.test_devtools_live_smoke",
        "tools.overworld.test_devtools_public_observation",
        "tools.overworld.test_devtools_jobs",
        "tools.overworld.test_devtools_evidence_stream",
        "tools.overworld.test_devtools_copy",
        "scripts.test_prune_overworld_session_roms",
        "tools.overworld.test_devtools_test_efficiency",
        "tools.overworld.test_devtools_prepared_boundary",
        "tools.overworld.test_devtools_prepared_sequence",
        "tools.overworld.test_devtools_release_observer",
        "tools.overworld.test_devtools_watchdog",
        "tools.overworld.test_devtools_engine",
        "tools.overworld.test_melonds_backend",
        "tools.overworld.test_melonds_backend_policy",
        "tools.overworld.test_devtools_binding_context",
        "tools.overworld.test_devtools_binding_measurement",
        "tools.overworld.test_devtools_mount_begin_measurement",
        "tools.overworld.test_mount_terminal_field_input",
        "tools.overworld.test_devtools_mount_pacing_observer",
        "tools.overworld.test_devtools_mount_pacing_command",
        "tools.overworld.test_devtools_mount_pacing_contract",
        "tools.overworld.test_devtools_mount_pacing_measurement",
        "tools.overworld.test_devtools_mount_pacing_control",
        "tools.overworld.test_devtools_mount_pose_control_measurement",
        "tools.overworld.test_devtools_mount_pacing_proof",
        "tools.overworld.test_devtools_mount_control_stress",
        "tools.overworld.test_devtools_mount_control_stress_proof",
        "tools.overworld.test_devtools_wild_walk_observer",
        "tools.overworld.test_devtools_wild_walk_command",
        "tools.overworld.test_devtools_wild_walk_control",
        "tools.overworld.test_devtools_wild_walk_measurement",
        "tools.overworld.test_devtools_wild_walk_contract",
        "tools.overworld.test_devtools_wild_walk_proof",
        "tools.overworld.test_devtools_wild_clear_control_measurement",
        "tools.overworld.test_devtools_wild_clear_control_proof",
        "tools.overworld.test_shared_binding_controller",
        "tools.overworld.test_devtools_native_free_guard",
        "tools.overworld.test_devtools_runtime_health",
        "tools.overworld.test_devtools_callback_costs",
        "tools.overworld.test_devtools_dispatch_counts",
        "tools.overworld.test_devtools_host_probe",
        "tools.overworld.test_devtools_phase_timings",
        "tools.overworld.test_devtools_snapshot_probe",
        "tools.overworld.test_devtools_spawn_cost_probe",
        "tools.overworld.test_devtools_sampler_costs",
        "tools.overworld.test_devtools_callback_costs_wiring",
        "tools.overworld.test_devtools_observation_prepare",
        "tools.overworld.test_devtools_resolver_parity",
        "tools.overworld.test_devtools_resolver_probe",
        "tools.overworld.test_devtools_actor_inspect_probe",
        "tools.overworld.test_devtools_actor_inspect_command",
        "tools.overworld.test_devtools_walk_reset",
        "tools.overworld.test_devtools_walk_reset_command",
        "tools.overworld.test_devtools_mount_walk_fixture",
        "tools.overworld.test_devtools_mount_walk_fixture_command",
        "tools.overworld.test_devtools_corner_observer",
        "tools.overworld.test_devtools_corner_command",
        "tools.overworld.test_devtools_walk_matrix_command",
        "tools.overworld.test_devtools_stomp_command",
        "tools.overworld.test_devtools_mounted_crash_command",
        "tools.overworld.test_devtools_mounted_crash_observer",
        "tools.overworld.test_devtools_crash_test_support",
        "tools.overworld.test_devtools_crash_typed_integration",
        "tools.overworld.test_devtools_stomp_observer",
        "tools.overworld.test_devtools_stomp_control",
        "tools.overworld.test_devtools_stomp_contract",
        "tools.overworld.test_devtools_stomp_measurement",
        "tools.overworld.test_devtools_stomp_control_measurement",
        "tools.overworld.test_devtools_stomp_proof",
        "tools.overworld.test_devtools_stomp_control_proof",
        "tools.overworld.test_devtools_stomp_recipe",
        "tools.overworld.test_devtools_walk_matrix_contract",
        "tools.overworld.test_devtools_walk_matrix_observer",
        "tools.overworld.test_devtools_walk_matrix_measurement",
        "tools.overworld.test_devtools_walk_matrix_control",
        "tools.overworld.test_devtools_walk_matrix_control_measurement",
        "tools.overworld.test_devtools_walk_matrix_control_proof",
        "tools.overworld.test_devtools_walk_matrix_proof",
        "tools.overworld.test_devtools_walk_matrix_recipe",
        "tools.overworld.test_devtools_corner_probe",
        "tools.overworld.test_devtools_corner_contract",
        "tools.overworld.test_devtools_corner_measurement",
        "tools.overworld.test_devtools_corner_proof",
        "tools.overworld.test_devtools_corner_control",
        "tools.overworld.test_devtools_corner_control_measurement",
        "tools.overworld.test_mounted_diagonal_rejection",
        "tools.overworld.test_mount_hop_candidate_search",
        "tools.overworld.test_devtools_walk_reset_oracle",
        "tools.overworld.test_devtools_walk_intent",
        "tools.overworld.test_devtools_walk_intent_command",
        "tools.overworld.test_devtools_walk_policy_control",
        "tools.overworld.test_devtools_walk_policy_control_measurement",
        "tools.overworld.test_devtools_walk_policy_control_proof",
        "tools.overworld.test_shared_walk_registration",
        "tools.overworld.test_devtools_teleport_boundary",
        "tools.overworld.test_devtools_empty_trace_boundary",
        "tools.overworld.test_devtools_acceleration_measurement",
        "tools.overworld.test_devtools_acceleration_contract",
        "tools.overworld.test_devtools_acceleration_proof",
        "tools.overworld.test_devtools_acceleration_acceptance",
        "tools.overworld.test_shared_acceleration_reset_controller",
        "tools.overworld.test_devtools_actor_inspect_contract",
        "tools.overworld.test_devtools_actor_inspect_measurement",
        "tools.overworld.test_shared_actor_inspect_controller",
        "tools.overworld.test_devtools_resolver_auth",
        "tools.overworld.test_devtools_resolver_discovery",
        "tools.overworld.test_devtools_resolver_command",
        "tools.overworld.test_devtools_role_profile",
        "tools.overworld.test_devtools_role_profile_command",
        "tools.overworld.test_devtools_role_profile_proof",
        "tools.overworld.test_shared_role_profile_controller",
        "tools.overworld.test_devtools_prepared_handoff",
        "tools.overworld.test_devtools_resolver_measurement",
        "tools.overworld.test_devtools_resolver_proof",
        "tools.overworld.test_shared_resolver_controller",
        "tools.overworld.test_devtools_manifest_size",
        "tools.overworld.test_devtools_runtime_health_wiring",
        "tools.overworld.test_devtools_input_phase",
        "tools.overworld.test_devtools_field_lifecycle",
        "tools.overworld.test_devtools_field_cleanup",
        "tools.overworld.test_devtools_field_availability",
        "tools.overworld.test_field_transition_reload",
        "tools.overworld.test_rebind_pass_through",
        "tools.overworld.test_motion_boundary_receipt",
        "tools.overworld.test_crash_presentation",
        "tools.overworld.test_devtools_crash_presentation",
        "tools.overworld.test_devtools_crash_measurement",
        "tools.overworld.test_grass_effect_guard",
        "tools.overworld.test_devtools_center_measurement",
        "tools.overworld.test_devtools_cyndaquil_setup_measurement",
        "tools.overworld.test_devtools_raw_chunk",
        "scripts.test_verify_overworld_walk_helper_alignment",
        "tools.overworld.test_spawn_metadata_cleanup",
        "tools.overworld.test_spawn_metadata_capacity",
        "tools.overworld.test_devtools_terrain",
        "tools.overworld.test_wild_walk_source_checks",
        "tools.overworld.test_devtools_chain_measurement",
        "tools.overworld.test_devtools_spawn_measurement",
        "tools.overworld.test_devtools_spawn_surface_measurement",
        "tools.overworld.test_devtools_spawn_surface_integration",
        "tools.overworld.test_devtools_surface_contract",
        "tools.overworld.test_devtools_pool_contract",
        "tools.overworld.test_pool_spawn_resolution",
        "tools.overworld.test_spawn_hop_origin",
        "tools.overworld.test_wild_occupancy",
        "tools.overworld.test_overlay153_occupancy_tail",
        "tools.overworld.test_devtools_cadence_measurement",
        "tools.overworld.test_player_collision_abi",
        "tools.overworld.test_player_collision_observer",
        "tools.overworld.test_devtools_player_collision_wait",
        "tools.overworld.test_cadence_collision_wait",
        "tools.overworld.test_devtools_cadence_integration",
        "tools.overworld.test_devtools_cadence_completion",
        "tools.overworld.test_devtools_compact_reports",
        "tools.overworld.test_devtools_prepared_retention",
        "tools.overworld.test_devtools_route_control",
        "tools.overworld.test_devtools_route_control_wiring",
        "tools.overworld.test_devtools_route_control_measurement",
        "tools.overworld.test_route_control_proof",
        "tools.overworld.test_route_control_negatives",
        "tools.overworld.test_route_cadence_proof",
        "tools.overworld.test_route_cadence_negatives",
        "tools.overworld.test_shared_cadence_controller",
        "tools.overworld.test_devtools_measurement_contract",
        "tools.overworld.test_devtools_movement_predicates",
        "tools.overworld.test_devtools_dialogue_predicate",
        "tools.overworld.test_devtools_dialogue",
        "tools.overworld.test_devtools_dialogue_wiring",
        "tools.overworld.test_devtools_d1_workflow",
        "tools.overworld.test_devtools_retirement",
        "tools.overworld.test_devtools_test_contract",
        "tools.overworld.test_devtools_test_proof",
        "tools.overworld.test_devtools_observer",
        "tools.overworld.test_devtools_reposition_observer",
        "tools.overworld.test_devtools_spawn_height_observer",
        "tools.overworld.test_devtools_spawn_height_control",
        "tools.overworld.test_devtools_spawn_height_control_wiring",
        "tools.overworld.test_devtools_spawn_height_control_measurement",
        "tools.overworld.test_shared_pool_surface_controller",
        "tools.overworld.test_shared_height_control_controller",
        "tools.overworld.test_devtools_replay_copy_on_write",
        "tools.overworld.test_devtools_observer_control",
        "tools.overworld.test_devtools_observer_control_measurement",
        "tools.overworld.test_devtools_insight",
        "tools.overworld.test_summary_native_transport",
        "tools.overworld.test_actor_binding_observer",
)


def _selected_tests(argv: list[str] | None = None) -> list[str]:
    parser = argparse.ArgumentParser(
        description="Run the full overworld host proof suite or named tests from it."
    )
    parser.add_argument(
        "--test",
        action="append",
        dest="tests",
        metavar="MODULE",
        help="Run one listed test module. Repeat for more modules.",
    )
    args, unknown = parser.parse_known_args(argv)
    if "--host-only" in unknown:
        parser.error(
            "all tests in this script are host-only; use --test MODULE for a narrow run"
        )
    if unknown:
        parser.error(f"unrecognized arguments: {' '.join(unknown)}")
    selected = args.tests or list(TESTS)
    invalid = [name for name in selected if name not in TESTS]
    if invalid:
        parser.error(
            "--test must name a module in the proof suite: " + ", ".join(invalid)
        )
    return selected


def main(argv: list[str] | None = None) -> int:
    suite = unittest.defaultTestLoader.loadTestsFromNames(_selected_tests(argv))
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
