#ifndef OVERWORLD_WILD_MOVEMENT_H
#define OVERWORLD_WILD_MOVEMENT_H

#include "types.h"

#define OW_WILD_MOVE_CUSTOM_AI 47
#define OW_WILD_MOVE_STOCK_WANDER 3

#define OW_WILD_MOVEMENT_PARAM_COOLDOWN 0
#define OW_WILD_MOVEMENT_PARAM_BEHAVIOR 1
#define OW_WILD_MOVEMENT_PARAM_RENDER 2

#define OW_WILD_MOVEMENT_BEHAVIOR_CHASE_PLAYER 1
#define OW_WILD_MOVEMENT_BEHAVIOR_FLEE_PLAYER 2

void LONG_CALL OverworldWildCustomMovement_SetFieldSystem(struct FieldSystem *fieldSystem);

#endif
