#!/usr/bin/env python3

import argparse
import re
import shutil
from pathlib import Path


SHINY_TAG_OFFSET = 5000
SHINY_GFX_START = 1553

PREFERRED_SHINY_GFX_BY_TAG = {
    447: 1553,  # Rattata
    530: 1554,  # Tentacool
    606: 1555,  # Magikarp
    646: 1556,  # Hoothoot
    650: 1557,  # Spinarak
}

SPECIES_ALIASES = {
    "SPECIES_MIMEJR": "SPECIES_MIME_JR",
}


def read_text(path):
    return Path(path).read_text(errors="ignore")


def normalize_species(species):
    return SPECIES_ALIASES.get(species, species)


def parse_species_order(path):
    order = {}
    for line in read_text(path).splitlines():
        match = re.match(r"#define\s+(SPECIES_[A-Z0-9_]+)\s+(.+)", line)
        if not match:
            continue
        value = match.group(2).split()[0]
        try:
            order[match.group(1)] = int(value, 0)
        except ValueError:
            pass
    return order


def parse_species_to_overworld(path):
    mapping = {}
    for line in read_text(path).splitlines():
        match = re.search(r"\[(SPECIES_[A-Z0-9_]+)\s*\]\s*=\s*(\d+)", line)
        if match:
            mapping[match.group(1)] = int(match.group(2))
    return mapping


def parse_overworld_rows(path):
    rows = {}
    for line in read_text(path).splitlines():
        match = re.search(
            r"\.tag\s*=\s*(\d+).*?\.gfx\s*=\s*(\d+).*?\.callback_params\s*=\s*([^},]+)",
            line,
        )
        if not match:
            continue
        tag = int(match.group(1))
        if tag >= SHINY_TAG_OFFSET:
            continue
        rows[tag] = {
            "gfx": int(match.group(2)),
            "callback": match.group(3).strip(),
        }
    return rows


def parse_encounter_species(paths):
    species = set()
    for path in paths:
        for raw_species in re.findall(r"SPECIES_[A-Z0-9_]+", read_text(path)):
            normalized = normalize_species(raw_species)
            if normalized != "SPECIES_NONE":
                species.add(normalized)
    return species


def has_shiny_palette(asset_dir, gfx):
    stem = f"{gfx:04d}"
    required = [
        f"{stem}.png",
        f"{stem}.json",
        f"{stem}-tsure_poke0.pal",
        f"{stem}-tsure_poke1.pal",
    ]
    return all((asset_dir / name).exists() for name in required)


def collect_entries(args):
    asset_dir = Path(args.asset_dir)
    species_order = parse_species_order(args.species_constants)
    species_to_ow = parse_species_to_overworld(args.species_to_ow)
    overworld_rows = parse_overworld_rows(args.overworld_table)
    encounter_species = parse_encounter_species(args.encounter_sources)

    entries = []
    for species in sorted(encounter_species, key=lambda item: species_order.get(item, 99999)):
        if species not in species_to_ow:
            continue
        tag = 428 + species_to_ow[species]
        if tag not in overworld_rows:
            continue
        row = overworld_rows[tag]
        if not has_shiny_palette(asset_dir, row["gfx"]):
            continue
        entries.append(
            {
                "species": species,
                "tag": tag,
                "shiny_tag": tag + SHINY_TAG_OFFSET,
                "gfx": row["gfx"],
                "callback": row["callback"],
            }
        )

    shiny_gfx_by_normal_gfx = {}
    used_shiny_gfx = set()

    for entry in entries:
        preferred = PREFERRED_SHINY_GFX_BY_TAG.get(entry["tag"])
        if preferred is None:
            continue
        if entry["gfx"] not in shiny_gfx_by_normal_gfx and preferred not in used_shiny_gfx:
            shiny_gfx_by_normal_gfx[entry["gfx"]] = preferred
            used_shiny_gfx.add(preferred)

    next_shiny_gfx = SHINY_GFX_START

    for entry in entries:
        normal_gfx = entry["gfx"]
        if normal_gfx not in shiny_gfx_by_normal_gfx:
            while next_shiny_gfx in used_shiny_gfx:
                next_shiny_gfx += 1
            shiny_gfx_by_normal_gfx[normal_gfx] = next_shiny_gfx
            used_shiny_gfx.add(next_shiny_gfx)
            next_shiny_gfx += 1

        entry["shiny_gfx"] = shiny_gfx_by_normal_gfx[normal_gfx]

    return entries


def write_if_changed(path, contents):
    path = Path(path)
    if path.exists() and path.read_text() == contents:
        return
    path.write_text(contents)


def generate_includes(args):
    entries = collect_entries(args)

    field_lines = [
        "/* Generated by tools/generate_shiny_overworld_variants.py. */",
    ]
    for entry in entries:
        field_lines.append(
            "    { .tag = %4d, .gfx = %4d, .callback_params = %s}, // shiny %s"
            % (entry["shiny_tag"], entry["shiny_gfx"], entry["callback"], entry["species"])
        )
    field_lines.append("")

    sprite_lines = [
        "/* Generated by tools/generate_shiny_overworld_variants.py. */",
    ]
    for entry in entries:
        sprite_lines.append("    %d, // %s" % (entry["tag"], entry["species"]))
    sprite_lines.append("")

    write_if_changed(args.field_include, "\n".join(field_lines))
    write_if_changed(args.sprite_include, "\n".join(sprite_lines))


def generate_assets(args):
    entries = collect_entries(args)
    asset_dir = Path(args.asset_dir)
    generated_dir = Path(args.generated_dir)
    if generated_dir.exists():
        shutil.rmtree(generated_dir)
    generated_dir.mkdir(parents=True)

    generated_gfx = {}
    for entry in entries:
        generated_gfx.setdefault(entry["shiny_gfx"], entry["gfx"])

    for shiny_gfx, normal_gfx in sorted(generated_gfx.items()):
        normal_stem = f"{normal_gfx:04d}"
        shiny_stem = f"{shiny_gfx:04d}"
        shutil.copyfile(asset_dir / f"{normal_stem}.png", generated_dir / f"{shiny_stem}.png")
        shutil.copyfile(asset_dir / f"{normal_stem}.json", generated_dir / f"{shiny_stem}.json")
        shutil.copyfile(
            asset_dir / f"{normal_stem}-tsure_poke1.pal",
            generated_dir / f"{shiny_stem}-tsure_poke0.pal",
        )
        shutil.copyfile(
            asset_dir / f"{normal_stem}-tsure_poke0.pal",
            generated_dir / f"{shiny_stem}-tsure_poke1.pal",
        )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["includes", "assets"], required=True)
    parser.add_argument("--asset-dir", default="data/graphics/overworlds")
    parser.add_argument("--generated-dir", default="build/generated_shiny_overworlds")
    parser.add_argument("--species-constants", default="include/constants/species.h")
    parser.add_argument("--species-to-ow", default="data/SpeciesToOWGfx.c")
    parser.add_argument("--overworld-table", default="src/field/overworld_table.c")
    parser.add_argument("--field-include", default="src/field/generated_shiny_overworld_table.inc")
    parser.add_argument(
        "--sprite-include",
        default="src/overworld_wild_spawns_overlay/generated_shiny_overworld_sprite_ids.inc",
    )
    parser.add_argument(
        "--encounter-sources",
        nargs="+",
        default=["armips/data/encounters.s", "armips/data/headbutt.s"],
    )
    args = parser.parse_args()

    if args.mode == "includes":
        generate_includes(args)
    else:
        generate_assets(args)


if __name__ == "__main__":
    main()
