#!/usr/bin/env python3

import argparse
import re
import shutil
from pathlib import Path


SHINY_TAG_OFFSET = 5000
SHINY_GFX_START = 1553

PREFERRED_SHINY_GFX_BY_TAG = {
    447: 1553,  # Rattata
    530: 1554,  # Tentacool
    606: 1555,  # Magikarp
    646: 1556,  # Hoothoot
    650: 1557,  # Spinarak
}


def read_text(path):
    return Path(path).read_text(errors="ignore")


def parse_pokemon_overworld_rows(path):
    rows = []
    in_pokemon_section = False
    for line in read_text(path).splitlines():
        if "pokémon follower specific overworlds start here" in line:
            in_pokemon_section = True
            continue
        if not in_pokemon_section:
            continue
        if "generated_shiny_overworld_table.inc" in line or "0xFFFF" in line:
            break

        match = re.search(
            r"\.tag\s*=\s*(\d+).*?\.gfx\s*=\s*(\d+).*?\.callback_params\s*=\s*([^},]+)",
            line,
        )
        if not match:
            continue
        tag = int(match.group(1))
        if tag >= SHINY_TAG_OFFSET:
            continue
        comment = ""
        if "//" in line:
            comment = line.split("//", 1)[1].strip()
        rows.append(
            {
                "tag": tag,
                "shiny_tag": tag + SHINY_TAG_OFFSET,
                "gfx": int(match.group(2)),
                "callback": match.group(3).strip(),
                "comment": comment or f"tag {tag}",
            }
        )
    return rows


def has_shiny_palette(asset_dir, gfx):
    stem = f"{gfx:04d}"
    required = [
        f"{stem}.png",
        f"{stem}.json",
        f"{stem}-tsure_poke0.pal",
        f"{stem}-tsure_poke1.pal",
    ]
    return all((asset_dir / name).exists() for name in required)


def collect_entries(args):
    asset_dir = Path(args.asset_dir)

    entries = []
    for entry in parse_pokemon_overworld_rows(args.overworld_table):
        if not has_shiny_palette(asset_dir, entry["gfx"]):
            continue
        entries.append(entry)

    shiny_gfx_by_normal_gfx = {}
    used_shiny_gfx = set()

    for entry in entries:
        preferred = PREFERRED_SHINY_GFX_BY_TAG.get(entry["tag"])
        if preferred is None:
            continue
        if entry["gfx"] not in shiny_gfx_by_normal_gfx and preferred not in used_shiny_gfx:
            shiny_gfx_by_normal_gfx[entry["gfx"]] = preferred
            used_shiny_gfx.add(preferred)

    next_shiny_gfx = SHINY_GFX_START

    for entry in entries:
        normal_gfx = entry["gfx"]
        if normal_gfx not in shiny_gfx_by_normal_gfx:
            while next_shiny_gfx in used_shiny_gfx:
                next_shiny_gfx += 1
            shiny_gfx_by_normal_gfx[normal_gfx] = next_shiny_gfx
            used_shiny_gfx.add(next_shiny_gfx)
            next_shiny_gfx += 1

        entry["shiny_gfx"] = shiny_gfx_by_normal_gfx[normal_gfx]

    return entries


def write_if_changed(path, contents):
    path = Path(path)
    if path.exists() and path.read_text() == contents:
        return
    path.write_text(contents)


def generate_includes(args):
    entries = collect_entries(args)

    field_lines = [
        "/* Generated by tools/generate_shiny_overworld_variants.py. */",
    ]
    for entry in entries:
        field_lines.append(
            "    { .tag = %4d, .gfx = %4d, .callback_params = %s}, // shiny %s"
            % (entry["shiny_tag"], entry["shiny_gfx"], entry["callback"], entry["comment"])
        )
    field_lines.append("")

    sprite_lines = [
        "/* Generated by tools/generate_shiny_overworld_variants.py. */",
    ]
    for entry in entries:
        sprite_lines.append("    %d, // %s" % (entry["tag"], entry["comment"]))
    sprite_lines.append("")

    write_if_changed(args.field_include, "\n".join(field_lines))
    write_if_changed(args.sprite_include, "\n".join(sprite_lines))


def generate_assets(args):
    entries = collect_entries(args)
    asset_dir = Path(args.asset_dir)
    generated_dir = Path(args.generated_dir)
    if generated_dir.exists():
        shutil.rmtree(generated_dir)
    generated_dir.mkdir(parents=True)

    generated_gfx = {}
    for entry in entries:
        generated_gfx.setdefault(entry["shiny_gfx"], entry["gfx"])

    for shiny_gfx, normal_gfx in sorted(generated_gfx.items()):
        normal_stem = f"{normal_gfx:04d}"
        shiny_stem = f"{shiny_gfx:04d}"
        shutil.copyfile(asset_dir / f"{normal_stem}.png", generated_dir / f"{shiny_stem}.png")
        shutil.copyfile(asset_dir / f"{normal_stem}.json", generated_dir / f"{shiny_stem}.json")
        shutil.copyfile(
            asset_dir / f"{normal_stem}-tsure_poke1.pal",
            generated_dir / f"{shiny_stem}-tsure_poke0.pal",
        )
        shutil.copyfile(
            asset_dir / f"{normal_stem}-tsure_poke0.pal",
            generated_dir / f"{shiny_stem}-tsure_poke1.pal",
        )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["includes", "assets"], required=True)
    parser.add_argument("--asset-dir", default="data/graphics/overworlds")
    parser.add_argument("--generated-dir", default="build/generated_shiny_overworlds")
    parser.add_argument("--overworld-table", default="src/field/overworld_table.c")
    parser.add_argument("--field-include", default="src/field/generated_shiny_overworld_table.inc")
    parser.add_argument(
        "--sprite-include",
        default="src/overworld_wild_spawns_overlay/generated_shiny_overworld_sprite_ids.inc",
    )
    args = parser.parse_args()

    if args.mode == "includes":
        generate_includes(args)
    else:
        generate_assets(args)


if __name__ == "__main__":
    main()
